<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'Non hai specificato dove cercare, ritenta.',
	602	=>	'Non hai specificato cosa cercare, ritenta.',
	603	=>	'Sii più specifico',
	604	=>	'Nessun risultato, ritenta.',
	605	=>	'La tua richiesta corrisponde a %d messaggi.',
	606	=>	'Puoi cercare messaggi che contengono un certo testo nelle tue cartelle della posta. Puoi effettuare una ricerca in base al <u>Mittente</u>, <u>Oggetto</u> e <u>Testo</u> dei messaggi. Seleziona le mailbox in cui cercare, inserisci il testo, e clicca sul bottone <b>Cerca</b>.<br><br>Cerca <b>non</b> è sensibile alle maiuscole o minuscole. Se inserisci più di una parola chiave, saranno trovati solo i messaggi contenenti quelle parole chiave in quello specifico ordine.',
	607	=>	'Testo',
	608	=>	'Oggetto',
	609	=>	'Mittente',
	610	=>	'<not used>',
	611	=>	'Cerca',
	612	=>	'Non hai specificato le mailbox in cui cercare.',
	613	=>	'Data'
);
?>
