<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Sì',
	2	=>	'No',
	3	=>	'Seleziona',
	4	=>	'Devi attivare il JavaScript nel tuo browser per usare BasiliX in modo efficiente',
	5	=>	'Devi attivare il supporto CSS nel tuo browser per usare BasiliX in modo efficiente',
	6	=>	'Devi attivare il supporto Cookie nel tuo browser per usare BasiliX in modo efficiente',
	7	=>	'Sconosciuto',
	8	=>	'Stampa',
	9	=>	'Chiudi finestra',
	10	=>	'Numero utenti presenti al momento: %d'
);
?>
