<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Il tuo indirizzo e-mail',
	52	=>	'Password',
	53	=>	'Login',
	54	=>	'Inserisci la tua password per il re-login',
	55	=>	'Cambia user',
	56	=>	'Connessione sicura (potrebbe essere lenta)',
	57	=>	'Connessione non sicura',
	58	=>	'Riempire tutti i campi.',
	59	=>	'Inserisci il tuo indirizzo email correttamente.',
	60	=>	'Inserisci la tua password.',
	61	=>	'Password errata o indirizzo e-mail inesistente.',
	62	=>	'Change domain'
);
?>
