<?
// Messages related with reading a message
$lang_msg["msgs"] = array(
	251	=>	'Da',
	252	=>	'A',
	253	=>	'Cc',
	254	=>	'Oggetto',
	255	=>	'Data',
	256	=>	'Testo del messaggio',
	257	=>	'Allegati:',
	258	=>	'<div align="center"><b>Il testo del messaggio è vuoto</b></div>',
	259	=>	'Impossibile trovare il messaggio specificato, potresti averlo eliminato!',
	260	=>	'Precedente',		// unused
	261	=>	'Successivo',		// unused
	262	=>	'Rispondi',
	263	=>	'Rispondi a tutti',
	264	=>	'Elimina',
	265	=>	'Inoltra',
	266	=>	'Mostra Intestazione',
	267	=>	'Nessun Oggetto',
	268	=>	'Salva Indirizzo',
	269	=>	'Messaggio HTML Formattato',
	270	=>	'Messaggio RFC822',
	271	=>	'Stato di consegna',
	272	=>	'Messaggio di testo semplice',
	273	=>	'Messaggio di testo arricchito',
	274	=>	'Allegato sconosciuto',
	275	=>	'Messaggio di testo',
	276	=>	'Applicazione',
	277	=>	'File Audio',
	278	=>	'Immagine',
	279	=>	'Video Clip',
	280	=>	'Firma PGP',
	281	=>	'Message Body'
);
?>
