<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'Vous n\'avez pas spécifié où chercher, essayez à nouveau.',
	602	=>	'Vous n\'avez pas spécifié quoi chercher, essayez à nouveau.',
	603	=>	'Soyez plus précis',
	604	=>	'Aucun résultat trouvé, essayez à nouveau.',
	605	=>	'%d messages correspondent à votre requête.',
	606	=>	'Vous pouvez chercher dans vos dossiers de courrier les messages qui contiennent un certain texte. Vous pouvez lancer la recherche sur les parties <u>De</u>, <u>Sujet</u> et <u>Corps</u> des messages. Choisissez les boites aux lettres sur lesquelles portera la recherche, entrez le texte à chercher, et cliquez sur le bouton <b>Recherche</b>. <br><br>La recherche <b>n\'est pas</b> sensible à la casse, et si vous entrez plus d\'un mot-clé, seuls les messages contenant ces mots-clés dans l\'ordre spécifié seront trouvés.',
	607	=>	'Corps',
	608	=>	'Sujet',
	609	=>	'De',
	610	=>	'<pas utilisé>',
	611	=>	'Recherche',
	612	=>	'Vous n\'avez pas spécifié les boites aux lettres dans lesquelles chercher.',
	613	=>	'Date'
);
?>
