<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Oui',
	2	=>	'Non',
	3	=>	'sélectionnez s\'il vous plaît',
	4	=>	'Vous devez activer JavaScript sur votre navigateur pour utiliser BasiliX de manière efficace',
	5	=>	'Vous devez activer le support de CSS sur votre navigateur pour utiliser BasiliX de manière efficace',
	6	=>	'Vous devez activer le support des Cookies pour utiliser BasiliX de manière efficace',
	7	=>	'Inconnu',
	8	=>	'Imprimer',
	9	=>	'Fermer la fenêtre',
	10	=>	'Nombre d\'utilisateurs connectés: %d'
);
?>
