<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Votre adresse E-mail',
	52	=>	'Mot de passe',
	53	=>	'Login',
	54	=>	'Resaisissez votre mot de passe',
	55	=>	'Changez d\'utilisateur',
	56	=>	'Connexion sécurisée (peut être lent)',
	57	=>	'Connexion non sécurisée',
	58	=>	'Remplissez tous les champs, s\'il vous plaît.',
	59	=>	'Saisissez une adresse E-mail au bon format.',
	60	=>	'Saisissez votre mot de passe.',
	61	=>	'Mot de passe incorrect ou adresse E-mail invalide.'
);
?>
