<?
// Messages related with reading a message
$lang_msg["msgs"] = array(
	251	=>	'De',
	252	=>	'A',
	253	=>	'Cc',
	254	=>	'Sujet',
	255	=>	'Date',
	256	=>	'Corps du message',
	257	=>	'Attachements:',
	258	=>	'<div align="center"><b>Le corps du message est vide</b></div>',
	259	=>	'Le message spécifié n\'a pu être trouvé, peut-être l\'avez-vous détruit à l\'instant!',
	260	=>	'Précédent',		// unused
	261	=>	'Suivant',		// unused
	262	=>	'Répondre',
	263	=>	'Répondre à Tous',
	264	=>	'Supprimer',
	265	=>	'Transmettre',
	266	=>	'Voir l\'en-tête',
	267	=>	'Pas de Sujet',
	268	=>	'Sauvegarder l\'adresse',
	269	=>	'Message formaté HTML',
	270	=>	'Message RFC822 ',
	271	=>	'Statut de la remise',
	272	=>	'Message en format texte',
	273	=>	'Message en format texte enrichi',
	274	=>	'Attachement inconnu',
	275	=>	'Message texte',
	276	=>	'Application',
	277	=>	'Fichier Audio',
	278	=>	'Fichier Image',
	279	=>	'Fichier  Clip',
	280	=>	'Signature PGP',
	281	=>	'Message Body'
);
?>
