#!/usr/bin/perl
use CGI::Carp qw(fatalsToBrowser);
###########################################################################
# DATE:                   March 11, 2000
# PROGRAM:                LogAnalyzer.cgi
# DDESCRIPTION:           Parses log files generated by tracking program
#                         and presents the information in an easy to read
#	       				  format.
#
# COPYRIGHT 2000 by ICS Scripts. No portion of this script may be offered
# for re-sale or re-distribution without express written permission.
#
# http://www.icsave.com      info@icsave.com
#
###########################################################################
print "Content-type: text/html\n\n";
#############################
# Get all variables         #
#############################
eval {

require "default.cgi";
require "GetCookie.cgi";

};


if ($@) {
print "Error including required files: $@\n\n";
print "Make sure these files exist, permissions\n";
print "are set properly, and paths are set correctly.\n\n";
exit;
}


($numpages, $count, $shown, $TotalHits, $whichlog, $showagent, $showreferrer, $showip, $showkeywords, $colspan, $ActionToTake) = split(/\|/, $ENV{'QUERY_STRING'});
if ($numpages =~ /go/) {

		#Begin processing options when query_string indicates form submitted

		# Scan form for options selected
		&DoParseForm;

		# Retrieve variables and set any new ones
		&get_variables;

		# Scan, format, and display log entries
        if($ActionToTake eq "view"){
		&Main;
        }

		# Create New Log And Append Date
        if($ActionToTake eq "rotate"){
		&RotateLog;
        exit;
        }

		# Permanently Delete This Log
        if($ActionToTake eq "delete"){
		&DeleteLog;
        exit;
        }

		# Display Log In Raw Format
        if($ActionToTake eq "raw"){
		&RawLog;
        exit;
        }
		
 # We're done
   exit;
   }

    if($numpages > 1){
      &Main;
      exit;
    }

&GetCookie();
if($Auth ne "OK"){
       print "<META HTTP-EQUIV=\"Refresh\" Content = \"0\;";
       print "URL=ICSstart.cgi\">";
       exit;
       }

		# Show program options for selection
		&DoDisplayForm;
	
#-----------------------------------------------------------------#
sub DoDisplayForm {

print <<EndHTML;
<html>
<head>
  <title>LogAnalyzer</title>
</head>
<body bgcolor="#FFFFFF">
<center>
<br><br>
<table cellpadding="4" cellspacing="1" border="2" width=65%" bgcolor="#C0C0C0">
<tr>
<td>
<FORM METHOD=POST ACTION="$ENV{'SCRIPT_NAME'}?go">
<table cellpadding="2" cellspacing="0" border="0" width="100%">
<tr>
<td align="center" colspan="2"  bgcolor="#C0C0C0" valign="bottom">
<font color="#400060" size="4" face="Arial">Log Display and Maintenance</font>
</td>
</tr>
<tr>
<td align="right" colspan="2" bgcolor="#C0C0C0">
<font color="#000000" size="-2" face="Arial">LogAnalyzer v1.2</font>
</td>
</tr>
<tr>
<td align="right" bgcolor="#FBF3D9" colspan="2">
<font size="-2" face="verdana, arial" color="#FF0000">
[<a href="Navigation.cgi"><font size="-2" face="verdana, arial">Navigation</font></a>]
</font>
<font size="-2" face="verdana, arial" color="#FF0000">
[<a href="/$ICSHelp/la_help.html" target="popup" onclick="window.open('about:blank','popup','scrollbars=1,width=430,height=500');">
<font size="-2" face="verdana, arial">Help </font></a>]</font>
</td>
</tr>
<tr>
<td height="10" colspan="2" bgcolor="#FBF3D9">\&nbsp;</td></tr>
<tr>
<td align="right" bgcolor="#FBF3D9">
<font size="2" face="verdana, arial" color="#400060"><b>Choose A Log Fle:</b>\&nbsp;</font>
</td>
EndHTML

print "<td  bgcolor=\"#FBF3D9\">\n";
print "<select name=\"whichlog\">\n";
opendir(FILES,"$filepath/$IPDirectory");
@whichlog = sort(grep(!/^\.\.?$/,readdir(FILES)));
closedir(FILES);
 foreach $whichlog (@whichlog){
   unless($whichlog eq "IPlist.pl"){
   print "  <option value=\"$whichlog\">$whichlog</option>\n";
   }
  }
print "</select>\n";

print <<EndHTML;
</td>
</tr>

<tr>
<td align="right" bgcolor="#FBF3D9">
<font size="2" face="verdana, arial" color="#400060"><b>Action For This Log:</b>\&nbsp;</font>
</td>
<td bgcolor="#FBF3D9">
<select name="ActionToTake">
  <option selected value="view">Display</option>
  <option value="rotate">Rotate Log</option>
  <option value="delete">Delete Log</option>
  <option value="raw">Display Raw</option>
</select>
</td>
</tr>

<tr>
<td align="right" bgcolor="#FBF3D9">
<font size="2" face="verdana, arial" color="#400060"><b>Hits per page:</b>\&nbsp;
</td>
<td bgcolor="#FBF3D9">
<select name="numpages">
  <option selected value="20">20</option>
  <option value="50">50</option>
  <option value="100">100</option>
  <option value="150">150</option>
  <option value="200">200</option>
  <option value="250">250</option>
  <option value="500">500</option>
  <option value="750">750</option>
  <option value="1000">1000</option>
  <option value="2000">2000</option>
  <option value="3000">3000</option>
  <option value="4000">4000</option>
  <option value="999999999">All Hits</option>
</select>
</td>
</tr>
<tr>
<td align="right" bgcolor="#FBF3D9">
<font size="2" face="Verdana, Arial" color="#400060"><b>Include User Agent in report:\&nbsp;</b></font>
</td>
<td bgcolor="#FBF3D9">
<input type="checkbox" name="showagent" value="yes" checked>\&nbsp;<font size="-1" color="#C0C0C0">uncheck to disable</font>
</td>
</tr>
<tr>
<td align="right" bgcolor="#FBF3D9">
<font size="2" face="Verdana, Arial" color="#400060"><b>Include Referrer in report: \&nbsp;</b></font>
</td>
<td bgcolor="#FBF3D9">
<input type="checkbox" name="showreferrer" value="yes" checked>\&nbsp;<font size="-1" color="#C0C0C0">uncheck to disable</font>
</td>
</tr>
<tr>
<td align="right" bgcolor="#FBF3D9">
<font size="2" face="Verdana, Arial" color="#400060"><b>Include IP Address in report: \&nbsp;</b></font>
</td>
<td bgcolor="#FBF3D9">
<input type="checkbox" name="showip" value="yes" checked>\&nbsp;<font size="-1" color="#C0C0C0">uncheck to disable</font>
</td>
</tr>
<tr>
<td align="right" bgcolor="#FBF3D9">
<font size="2" face="Verdana, Arial" color="#400060"><b>Include Search Keywords in report: \&nbsp;</b></font>
</td>
<td bgcolor="#FBF3D9">
<input type="checkbox" name="showkeywords" value="yes" checked>\&nbsp;<font size="-1" color="#C0C0C0">uncheck to disable</font>
</td>
</tr>

<tr>
<td colspan="2" bgcolor="#EAEAD5">
&nbsp;
</td>
</tr>

<tr><td bgcolor="#EAEAD5" align="center" colspan="2" valign="bottom">
<input type="submit" value="Perform Action For This Log">
</td>
</tr>
<tr>
<td align="right" colspan="2" bgcolor="#C0C0C0">
<a href=""><font face=arial size="-2" color="#400060">YourSite.com, editable in LogAnalyzer.cgi</font></a>
</td>
</tr>
</table>
</td>
</tr>
</table>
</body>
</html>
EndHTML
exit;
}
#-------------------------------------------------------------#
sub DoParseForm {

   read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});

   # Split the name-value pairs
   @pairs = split(/&/, $buffer);

   foreach $pair (@pairs) {
      ($name, $value) = split(/=/, $pair);

      # Un-Webify plus signs and %-encoding
      $value =~ tr/+/ /;
      $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
      $value =~ s/<!--(.|\n)*-->//g;
      $value =~ s/<([^>]|\n)*>//g;
      $FORM{$name} = $value;
      }
   }

sub get_variables {
$colspan = 3;
   if ($FORM{'whichlog'}) {
      $whichlog = $FORM{'whichlog'};
	  }
   if ($FORM{'showagent'}) {
      $showagent = $FORM{'showagent'};
	  $colspan++;
      }
   if ($FORM{'showreferrer'}) {
      $showreferrer = $FORM{'showreferrer'};
	  $colspan++;
      }
   if ($FORM{'showip'}) {
      $showip = $FORM{'showip'};
	  $colspan++;
      }
   if ($FORM{'showkeywords'}) {
      $showkeywords = $FORM{'showkeywords'};
	  $colspan++;
      }
   if ($FORM{'numpages'}) {
      $numpages = $FORM{'numpages'};
      }
   if ($FORM{'ActionToTake'}) {
      $ActionToTake = $FORM{'ActionToTake'};
      }
   }

#--------------------------------------------------------------#
sub Main {

open (LOGFILE,"$filepath/$IPDirectory/$whichlog") || &dienice ("could not open $filepath/$IPDirectory/$whichlog, ensure permissions are set correctly and that the paths are correct");

@entry = <LOGFILE>;
$i = 0;
foreach $record (@entry){
        $found = "no";
        chop $record;
        ($logtime, $useragent, $ipaddress, $referrer, $pagerequested) = split(/\|/,$record);
        ($logtime, $host) = split(/\--/,$logtime);
         ($url,$keywords) = split(/\?/,$referrer);
         $url = substr ($url, 7,30);
         $useragent =~ s/\(([^)]|\n)*\)//g;
#        ($useragent, $uaurl) = split(/\(/,$useragent);
         $pagerequested = substr ($pagerequested, 7);
         ($throwaway, $pagerequested) = split(/\//, $pagerequested,2);
         $pagerequested = "/$pagerequested";
         @keywordlist = split(/&/,$keywords);

          foreach $pair(@keywordlist){
          if ($found ne "yes"){
           ($name, $value) = split(/=/,$pair);
           $value =~ tr/+/ /;
           $value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
           $name =~ s/^\s+//; 


             if ($name eq "query"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "search"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "ask"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "general"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "keyword"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "Keywords"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "UserName"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "q"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "MT"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "sn"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "sTerm"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "qt"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "qr"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "p"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "s"){
                 $keywords = $value;
                 $found = "yes";
                 }
             elsif ($name eq "box"){
                 $keywords = e-mail;
                 $found = "yes";
                 }
             elsif ($found ne "yes"){
                 $keywords = "n/a";
                 }

           }

   }

push @fileout, "$logtime|$useragent|$ipaddress|$url|$keywords|$pagerequested|$uaurl|$referrer";
$i++;

}
close(LOGFILE);

$TotalHits = $i;
$PagesToShow = $numpages;
$numpages = $numpages + $shown;

$count = 1;
	
print "<html><head><title>ICS Scripts LogAnalyzer</title></head>\n";
print "<body bgcolor=\"FFFFFF\">\n";
print "<center>";
print "<table cellspacing=\"1\" cellpadding=\"5\" border=\"1\" width=\"90%\">\n";
print "<tr><td bgcolor=\"#C0C0C0\" colspan=\"$colspan\" align=\"center\">\n";
print "<table cellspacing=\"1\" cellpadding=\"3\" border=\"0\" width=\"100%\">\n";
print "<tr><td bgcolor=\"#C0C0C0\" colspan=\"$colspan\" align=\"left\">\n";
print "<font face=\"Arial, Verdana, Bookman\" size=\"-1\">\n";
print "<h3><b>Log Analysis For</b>: <font color=\"#408080\" size=\"3\"><b>$DomainName</b></font><br><br>\n";

print "<b>Scanning:</b> <font color=\"#408080\" size=\"3\"><b>$whichlog</b></font><br>\n";

print "</h3></font>\n";
print "<font face=\"Arial, Verdana, Bookman\" size=\"3\"><b>Total Page Requests:</b></font> <font color=\"#408080\" size=\"2\"><b>$i</b></font><br>\n";
print "</td></tr>\n";
print "<tr><td bgcolor=\"#DADADA\" align=\"center\">\n";
print "<font face=\"Arial, Verdana, Bookman\" size=\"-1\">\n";
print "<b>Hit No.</b>\n";
print "</font>\n";
print "</td>\n";
print "<td bgcolor=\"#DADADA\" align=\"center\">\n";
print "<font face=\"Arial, Verdana, Bookman\" size=\"-1\">\n";
print "<b>Time</b>\n";
print "</font>\n";
print "</td>\n";
if ($showagent eq "yes"){
print "<td bgcolor=\"#DADADA\" align=\"center\">\n";
print "<font face=\"Arial, Verdana, Bookman\" size=\"-1\">\n";
print "<b>User Agent</b>\n";
print "</font>\n";
print "</td>\n";
}
if ($showip eq "yes"){
print "<td bgcolor=\"#DADADA\" align=\"center\">\n";
print "<font face=\"Arial, Verdana, Bookman\" size=\"-1\">\n";
print "<b>IP Address</b>\n";
print "</font>\n";
print "</td>\n";
}
if ($showreferrer eq "yes"){
print "<td bgcolor=\"#DADADA\" align=\"center\">\n";
print "<font face=\"Arial, Verdana, Bookman\" size=\"-1\">\n";
print "<b>Referrer</b>\n";
print "</font>\n";
print "</td>\n";
}
if ($showkeywords eq "yes"){
print "<td bgcolor=\"#DADADA\" align=\"center\">\n";
print "<font face=\"Arial, Verdana, Bookman\" size=\"-1\">\n";
print "<b>Keywords</b>\n";
print "</font>\n";
print "</td>\n";
}
print "<td bgcolor=\"#DADADA\" align=\"center\">\n";
print "<font face=\"Arial, Verdana, Bookman\" size=\"-1\">\n";
print "<b>Page Requested</b>\n";
print "</font>\n";
print "</td></tr>\n";
    foreach $recout (@fileout){
		($logtime, $useragent, $ipaddress, $url, $keywords, $pagerequested, $uaurl, $referrer) = split(/\|/,$recout);
        if($count >= $shown && $count <= $numpages){ 
        print "<tr><td bgcolor=\"#EAEAD5\" align=\"center\">\n";
        print "<font face=\"Arial, Verdana, Bookman\" size=\"-2\">\n";
        print "$count\n";
        print "</font>\n";
        print "</td>\n";
        print "<td bgcolor=\"#EAEAD5\" align=\"center\">\n";
        print "<font face=\"Arial, Verdana, Bookman\" size=\"-2\">\n";
        print "$logtime\n";
        print "</font>\n";
        print "</td>\n";
if ($showagent eq "yes"){
        if ($useragent eq ""){$useragent = "\&nbsp\;"}
        if ($uaurl =~ /AOL/){$useragent = "AOL"}
        print "<td bgcolor=\"#EAEAD5\" align=\"center\">\n";
        print "<font face=\"Arial, Verdana, Bookman\" size=\"-2\">\n";
        print "$useragent\n";
        print "</font>\n";
        print "</td>\n";
        }
if ($showip eq "yes"){
        print "<td bgcolor=\"#EAEAD5\" align=\"center\">\n";
        print "<font face=\"Arial, Verdana, Bookman\" size=\"-2\">\n";
        print "$ipaddress\n";
        print "</font>\n";
        print "</td>\n";
       }
if ($showreferrer eq "yes"){
        if ($url eq ""){$url = "no referer"}
        print "<td bgcolor=\"#EAEAD5\" align=\"center\">\n";
        print "<font face=\"Arial, Verdana, Bookman\" size=\"-2\">\n";
        if($url eq "no referer"){
           print "$url\n";
           }else{
            print "<a href=\"$referrer\" target=\"_new\">$url</a>\n";
            }
        print "</font>\n";
        print "</td>\n";
        }
if ($showkeywords eq "yes"){
        if ($keywords eq ""){$keywords = "\&nbsp\;"}
        print "<td bgcolor=\"#EAEAD5\" align=\"center\">\n";
        print "<font face=\"Arial, Verdana, Bookman\" size=\"-2\">\n";
        print "$keywords\n";
        print "</font>\n";
        print "</td>\n";
        }
        print "<td bgcolor=\"#EAEAD5\" align=\"center\">\n";
        print "<font face=\"Arial, Verdana, Bookman\" size=\"-2\">\n";
        print "$pagerequested\n";
        print "</font>\n";
        print "</td></tr>\n";
        }
       $count++;
 }

        print "<tr><td bgcolor=\"#C0C0C0\" align=\"center\" colspan=\"$colspan\">\n";
        print "<font face=\"Arial, Verdana, Bookman\" size=\"-2\">\n";
        $shown = $PagesToShow + $shown;

    if ($shown <= $PagesToShow){
        $ThisManyLinks = int($TotalHits/$numpages)+ 1;
        $lnknum = 1;
        print "<b>Go To Page</b>:\n";
          for ($x = 1; $x < $ThisManyLinks; $x++) {
               $lnknum++;
               $shown = $numpages * ($lnknum - 1);
               print "| <a href=\"LogAnalyzer.cgi?$PagesToShow|$count|$shown|$TotalHits|$whichlog|$showagent|$showreferrer|$showip|$showkeywords|$colspan|$ActionToTake\">$lnknum</a> |\n";
          }
        }else {
               unless($shown >= $TotalHits){
               print "| <a href=\"LogAnalyzer.cgi?$PagesToShow|$count|$shown|$TotalHits|$whichlog|$showagent|$showreferrer|$showip|$showkeywords|$colspan|$ActionToTake\">Next >>></a> |\n";
               }
         }
        print "<br><br><a href=\"LogAnalyzer.cgi\">Return To Log Interface</a>\n";
        print "&nbsp;\n";
        print "</font>\n";
        print "</td></tr>\n";

print "</td></tr>\n";		
print "</table>\n";		
print "</center>\n";
print "</table></body></html>\n";
}
#----------------------------------------------------------------------------#
sub RotateLog {

$when = localtime;
$when = substr($when, 0, 10);
$when =~ s/ //g;
$Savewhichlog = $whichlog;
open(LOGFILEROTATE,"$filepath/$IPDirectory/$whichlog") || &dienice ("could not open $filepath/$IPDirectory/$whichlog, ensure permissions are set correctly and that the paths are correct");

$whichlog =~ s/\.log//;
$whichlog = "$whichlog"."$when".".log";

open(ARCHIVE,">>$filepath/$IPDirectory/$whichlog") || &dienice ("could not open $filepath/$IPDirectory/$whichlog, ensure permissions are set correctly and that the paths are correct");

         while (<LOGFILEROTATE>) {

            print ARCHIVE $_,;
            }

close (LOGFILEROTATE);
close (ARCHIVE);

open(CLEARLOGFILE,">$filepath/$IPDirectory/$Savewhichlog") || &dienice ("could not open $filepath/$IPDirectory/$whichlog, ensure permissions are set correctly and that the paths are correct");

close(CLEARLOGFILE);

$TopError = "<b>Rotation Complete. <i>$Savewhichlog</i> has been cleared</b>";

&LogAction("<b>$whichlog</b> has been created and the contents of <b>$Savewhichlog</b> have been copied to it."); 

}
#----------------------------------------------------------------------------#
sub DeleteLog {

chdir "$filepath/$IPDirectory";

unlink $whichlog;

$TopError = "<b><i>$whichlog</i> Has Been Permanently Deleted</b>";

&LogAction("<b>$whichlog</b> and its contents have been deleted.");

}
#----------------------------------------------------------------------------#
sub RawLog {

open (LOGFILERAW,"$filepath/$IPDirectory/$whichlog") || &dienice ("could not open $filepath/$IPDirectory/$whichlog, ensure permissions are set correctly and that the paths are correct");

              while (<LOGFILERAW>) {

            print $_,"<br>\n";
            }

     close(LOGFILERAW);

}
#------------------------------------------------------------------#
sub LogAction {

    ($msg) = @_;
print <<EndOfHTML;
<html><head>
<title>Log Action</title>
</head>
<body bgcolor="FFFFFF">
<center>
<br><br>
<table cellspacing="1" cellpadding="4" border="2" bgcolor="#C0C0C0" width="70%">
<tr><td>
<table cellspacing="2" cellpadding="4" border="0" bgcolor="#EAEAD5" width="100%">
<tr>
<td align="center" bgcolor="#C0C0C0">
<font color="#400060" size="+1" face="Arial">Log Action</font>
</td>
</tr>
<tr>
<td height="10" bgcolor="#EAEAD5">
<br>
<font color="#008040" size="3" face="Arial"><b>Log Action Successful!</b></font>
</td>
</tr>
<tr>
<td align="left" bgcolor="#FBF3D9">
<font size="+4" face="verdana, arial" color="#008040">!</font>
<font size="-1" face="verdana, arial">$TopError;<br><br> $msg</font>
</td>
</tr>

<tr>
<td bgcolor="#EAEAD5">
&nbsp;
</td>
</tr>

<tr>
<td align="center" bgcolor="#EAEAD5">
[<a href="LogAnalyzer.cgi"><font face=arial size="-2" color="maroon">Log Analyzer Interface</font></a>]
</td>
</tr>

<tr>
<td align="right" colspan="2" bgcolor="#C0C0C0">
<a href=""><font face=arial size="-2" color="#400060">YourSite.com, editable in LogAnalyzer.cgi</font></a>
</td>
</tr>
</table>
</td>
</tr>
</table>
</body>
</html>
</body></html>
EndOfHTML
exit;
}
#----------------------------------------------------------------------------#

sub dienice {
    ($msg) = @_;
    print "<h2>Error</h2>\n";
    print "$msg";
    exit;
}