<?
/********************************************************

	AUTHOR: Ryo Chijiiwa <ryo@ilohamail.org>
	FILE: include/langs.inc
	PURPOSE:
		Provide centralized location for keeping track of available languages and character sets

********************************************************/

$languages=array(
	"eng/"=>"English",
	"tw/"=>"Chinese (BIG5)",
	"cn/"=>"Chinese(GB2312)",
	"dk/"=>"Dansk",
	"de/" => "Deutsch",
	"es/" => "Espa&ntilde;ol",
	"fr/"=>"Fran&ccedil;ais", 
	"it/"=>"Italiano",
	"jp/"=>"Japanese", 
	"nl/"=>"Nederlands",
	"pl/"=>"Polski",
	"br/"=>"Portuguese (Brazilian)",
	"se/"=>"Swedish"
);

$charsets=array(
	"US-ASCII"=>"ASCII (English)", 
	"X-EUC-JP"=>"EUC-JP (Japanese)", 
	"ISO-8859-1"=>"ISO-8859-1 (Latin-1)",
	"ISO-8859-2"=>"ISO-8895-2",
	"BIG5"=>"BIG5 (Chinese)",
	"GB2312"=>"GB2312 (Chinese)"
);
?>
