<?
/********************************************************
	lang/es/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings=array(
	0=>"Asunto",
	1=>"De",
	2=>"A",
	3=>"Copia",
	4=>"Copia Oculta",
	5=>"Fecha"
);

$composeStrings=array(
	0=>"Escribir Mensaje",
	1=>"Enviar Mensaje",
	2=>"Subir",
	3=>"Agregar Firma",
	4=>"Adjuntar",
	5=>"Mostrar Contactos",
	6=>"Ocultar Contactos",
	7=>"Cuerpo del mensaje:",
	8=>"A&ntilde;adir",
	9=>"Con fecha %d, %s escribió:\n",
	10=>"--- Mensaje Original ---\n",
    11=>"Close Window"
);

$composeErrors=array(
	0=>"El campo del asunto est&aacute; vac&iacute;o.  Por favor, escribe un asunto.",
	1=>"El campo \"de\" est&aacute; vac&iacute;o.  Por favor, introduce tu direcci&oacute;n de correo electr&oacute;nico.",
	2=>"El campo \"Para\" est&aacute; vac&iacute;o.  Por favor, especifica la direcci&oacute;n de destino.",
	3=>"Fallo al subir archivo",
	4=>"No se recibieron archivos.",
    5=>"Para prevenir el correo no deseado, solamente puedes enviar a %1 personas (%2 en total por sesi&oacute;n) cada %3 segundos."
);
?>
