<?
/********************************************************
	lang/es/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"Contactos",
	1=>"Agregar Contacto",
	2=>" Contacto",
	3=>"Nombre",
	4=>"Email",
	5=>"URL",
	6=>"Grupo",
	7=>"Comentarios",
	8=>"Agregar/Editar Contacto",
	9=>"Email",
    10=>"Compose"
);

$cErrors=array(
	0=>"La lista de contactos está vacía"
);
?>
