<?
/********************************************************
	lang/es/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime =  array(
	"dsow" => array (			
			0 => "Dom",
			1 => "Lun",
			2 => "Mar",
			3 => "Mie",
			4 => "Jue",
			5 => "Vie",
			6 => "Sab"
			),
	"today" => "Hoy %t",
	"lastweek" => "%w %t",
	"thisyear" => "%m/%d",
	"prevyears" => "%m/%d/%y"
);

?>
