<?
/********************************************************
	lang/es/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings=array(
	0=>"Administrar Carpetas",
	1=>"Crear nueva Carpeta",
	2=>"Crear Carpeta: ",
	3=>"Crear",
	4=>"Eliminar Carpeta",
	5=>"Eliminar",
	6=>"Renombrar Carpeta",
	7=>"Renombrar"
);

$errors=array(
	0=>"Crear Carpeta: ",
	1=>"No se pudo crear la carpeta: ",
	2=>"Carpeta Eliminada: ",
	3=>"No se pudo eliminar la carpeta: ",
	4=>"Carpeta renombrada: ",
	5=>"No se pudo renombrar carpeta: ",
	6=>"El soporte para carpetas sólo está disponible para cuentas IMAP."
);
?>
