<?
/********************************************************
	lang/es/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings=array(
	0=>"Editar",
	1=>"Agregar",
	2=>" Contacto",
	3=>"Nombre",
	4=>"Email",
	5=>"URL",
	6=>"Grupo",
	7=>"Comentarios",
	8=>"Teléfono de casa",
	9=>"Teléfono del trabajo",
	10=>"Teléfono celular",
	11=>"Dirección",
	12=>"Email alterno",
	13=>"Eliminar",
	14=>"Otro"
);

$errors=array(
	0=>"No se pudo agregar el contacto: error en la base de datos.",
	1=>"Ya existe un contacto con esa dirección.",
	2=>"Click ",
	3=>"aquí",
	4=>" para editar ese registro.",
	5=>"No se encontró al contacto, o se negó el acceso.",
	6=>"¿Estás seguro de que quieres eliminar el registro de \"",
	7=>"\"?"
);
?>
