<?
/********************************************************
	lang/es/prefs.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$prefHeaderStrings = array(
											0=> "Preferencias",
											1=>"General",
											2=>"Colores"
											);
											
$prefsStrings = array(
									"0.0" => "Identidad",
									"0.1" => "Nombre: ",
									"0.2" => "Email: ",
									"1.0" => "Internacional",
									"1.1" => "Interfaz: ",
									"1.2" => "Caracteres: ",
									"1.3" => "Horario: ",
									"2.0" => "Opciones de vista de lista",
									"2.1" => "Mostrar hasta ",
									"2.2" => " elementos",
									"2.3" => "Mostrar tamaño",
									"2.4" => "Ordenar por: ",
									"2.5" => "",
									"2.6" => "Orden: ",
									"2.7" => "",
									"2.8" => "Mostrar lista de carpetas",
									"3.0" => "Opciones de Auto-Guardado",
									"3.1" => "Guardar elementos envaidos.",
									"3.2"=> "Guardar elementos enviados en la carpeta: ",
									"3.3" => "",
									"3.4" => "Automaticamente eliminar basura",
									"3.5" => "Mover elementos eliminados a la carpeta: ",
									"3.6" => "",
									"3.7" => "Directorio Raiz: ",
									"3.8" => "Otro",
									"4.0" => "Opciones de ver mensaje",
									"4.1" => "Ver en frame",
									"4.2" => "Poner color a comillas",
									"4.3" => "Habilitar esta opción puede alentar el sistema.",
    					                                "4.4" => "Convertir URLs a ligas",
									"4.5" => "Mostrar mensajes en HTML",
									"4.6" => "Mostrar imágenes en el contexto",
									"5.0" => "Firma",
									"5.1" => "Mostrar la firma predeterminada",
									"5.2" => ""
									);

$sort_fields=array("DATE"=>"Fecha", "SUBJECT"=>"Asunto", "SIZE"=>"Tamaño");
$sort_orders=array("ASC"=>"Ascendente", "DESC"=>"Descendente");

$prefsButtonStrings = array( 0=> "Actualizar", 1=>"Aplicar", 2=> "Revertir", 3=> "Defaults");

$prefs_new_user = "Parece ser que es la primera vez que inicias sesión. ¡Bienvenido!<br>";
$prefs_new_user .= "Por favor, configura tu cuenta y posteriormente presiona \"Aplicar\"";
?>
