<?
/********************************************************
	lang/es/pref_colors.inc	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	This file is part of IlohaMail, and released under GPL.	See COPYING,
	or http://www.fsf.org/copyleft/gpl.html
********************************************************/
$pcStrings= array(							
			"0" => "Pon el código de color HTML para cada componente.",
			"0.1" => "Usa la ",
			"0.2" => "Gráfica de colores de códigos",
			"0.3" => " para encontrar el código de color correcto.",
			"1.0" => "Barra de Herramientas",
			"2.0" => "Lista de Carpetas",
			"3.0" => "Principal",
			"4.0" => "Misceláneo",
			"4.1" => "Citas: "
		);							
$pcPortions = array( "Background: ", "Links: ", "Text: ", "Hilight: ");?>
