<?
/********************************************************
	lang/es/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"Regresar",
	1=>"Responder",
	2=>"Reenviar",
	3=>"Recuperar",
	4=>"Eliminar",
	5=>"Archivo",
	6=>"Partes",
	7=>"Éste es un mensaje HTML. ",
	8=>"Haz click aquí para leerlo.",
	9=>"Fuente",
	10=>"Tamaño",
	11=>"Marcar como no leído",
	12=>"Mostrar encabezado",
	13=>"Reportar Abuso (Spam)",
	14=>"Responder a todos"
);
?>
