<?
/********************************************************
	lang/es/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors=array(
	"field"=>"Criterio de búsqueda inválido: Campo no válido",
	"empty"=>"Criterio de búsqueda inválido: Cadena de búsqueda vacía",
	"date"=>"Criterio de búsqueda inválido:  No se especificó fecha"
);
?>
