<?
/********************************************************
	lang/es/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings=array(
	"folders"=>"Carpetas",
	"inbox"=>"Bandeja de Entrada",
	"compose"=>"Redactar",
	"contacts"=>"Contactos",
	"search"=>"Buscar",
	"prefs"=>"Preferencias",
	"logout"=>"Salir",
	"go"=>"Ir"
);
?>
