<?php $complaint = "To Abuse Team at $count1.$count2,

Note1: This is an automatically generated message on $T PST/PDT (GMT $Toff).

Note2: This e-mail can only be generated by someone visiting any of our customers cgi-bin for example:

URL: /cgi-bin/formmail.pl?recipient=      or        /cgi-bin/formmail.cgi?recipient=

This script will not report a complaint without ?recipient= in the URL.

Note3: If you receive multiple complaints referencing the same IP number this is because your client has effectively reported themselves to you @ each time stamp that they are attempting illegal use of our services.

Note4: ntpd (network time protocol daemon) run daily, so the date / time stamp above and below is accurate.

$company would like to report that one of your users from $ip has attempted to use the infamous formmail hack to transmit UCE / Bulk e-mail using our systems. As a web hosting provider we do not allow any of our clients to use Matt Wright formmail script because of the possibility of our servers being used for UCE. In addition we would like to point out that a copy has been sent to us and refusal from $count1.$count2 to act on these complaints may subject them along with the perpetrators to the following California laws.

California Business and Professions Code §17538.45
Abstract: Allows an email service provider (i.e., companies or individuals running
a mail server) to recover statutory damages of $50 per message, up to $25,000 per
day, or its actual damages, whichever is greater.

California Penal Code §502
Abstract: As an amendment to the Computer Crimes Act, prohibits forging someone
else's domain name in e-mail. Violators are subject to criminal prosecution, and the
plaintiff can collect real damages.

Please take immediate action against this individual in accordance with your Acceptable Use Policy. We have no wish to initiate legal proceedings and would be very happy if $count1.$count2 discontinued service to this individual.

Below you will find the information retrieved from this script, all information provided should be enough to track down this individual. Please do not request our server logs, they would just reconfirm the information already provided. Once a spammer thinks they have an open formmail relay where they can send mass UCE through, many of them will attempt several thousand e-mails through our system in a single day. Which makes it impracticable for us to retrieve each IP number individually.

Sincerely,
Admin
$company
";?>


