#!/usr/bin/perl
###################################
##  AutoRank Professional v2.1.1 ##
###############################################################
##  help.cgi                                                 ##
##  --------                                                 ##
##  This script displays help files for the admin script.    ##
###############################################################

###############################################################
##                   DO NOT EDIT THIS FILE                   ##
###############################################################

use strict;

print "Content-type: text/html\n\n";

eval {
  &main;
};

if($@) {
  print "<b>Script Error:</b> $@";
}

exit;

sub main {
  require "functions.cgi";
  require "$fnct::sd_dir/help.dat";

  my(%tmpl, $qry);

  $qry = parse_query();
  
  $qry->{'page'} = ($qry->{'page'} eq "") ? "TOPICS" : $qry->{'page'};
  
  $tmpl{'HELP_DATA'} = $HELPINFO::PAGE{$qry->{'page'}};

  parse_tmpl("_admin_help.htmlt", \%tmpl);
}

sub parse_tmpl {
  my($page, $tmpl) = @_;

  open(FILE, "$fnct::tp_dir/$page") || fnct::serror($page, "parse_tmpl()", $!, undef);
  my @file_contents = <FILE>;
  close(FILE);

  
  for(@file_contents) {
    $_ =~ s/#%(.*?)%#/$tmpl->{$1}/gise;
  }

  print @file_contents;
}

sub parse_query {
  my @pairs = split(/&/, $ENV{'QUERY_STRING'});
  my ($name, $value, %query);
  
  for (@pairs) {
    ($name, $value) = split(/=/, $_);
    $query{$name} = $value;
  }
  
  return \%query;
}
