<?
// 'Mesaj ara' mesajlarý
$lang_msg["findmsg"] = array(
	601	=>	'Aranacak kýsmý seçmediniz, lütfen tekrar deneyiniz..',
	602	=>	'Aranacak kelimeyi girmediniz, lütfen tekrar deneyiniz..',
	603	=>	'Lütfen daha belirgin bir kelime giriniz.',
	604	=>	'Aramaya uygun mesaj bulunamadý, lütfen tekrar deneyiniz..',
	605	=>	'Aramanýz sonucu %d adet mesaj bulundu.',
	606	=>	'Posta kutularýnýzdaki mesajlar üzerinde, mesajlarýn <u>Kimden</u>, <u>Konu</u> ve <u>Ýçerik</u> kýsýmlarýný kullanarak arama yapabilirsiniz. Aranmasýný istediðiniz Posta Kutularýný seçin, aranmasýný istediðiniz kelimeyi ilgili kýsýma yazin ve <b>Ara</b> butonuna basýn.<br><br>Arama küçük/büyük ayrýmý yapmaz. Ayrýca birden çok kelime aratýrsaniz, ilgili kelimeleri ayný sýrayla arama yapýlacaktýr.',
	607	=>	'Ýçerik',
	608	=>	'Konu',
	609	=>	'Kimden',
	610	=>	'<not used>',
	611	=>	'Ara',
	612	=>	'Aranmasýný istediðiniz posta kutularýný seçmediniz.',
	613	=>	'Tarih',
	614	=>	'Mesaj Ara:'
);
?>
