<?
// Global mesajlar
$lang_msg["global"] = array(
	1	=>	'Evet',
	2	=>	'Hayýr',
	3	=>	'Seçiniz',
	4	=>	'BasiliX\'i verimli kullanabilmek için JavaScript desteðini aktif hale getirmelisiniz',
	5	=>	'BasiliX\'i verimli kullanabilmek için CSS desteðini aktif hale getirmelisiniz',
	6	=>	'BasiliX\'i verimli kullanabilmek için Cookie desteðini aktif hale getirmelisiniz',
	7	=>	'Bilinmiyor',
	8	=>	'Print',
	9	=>	'Pencereyi kapat',
	10	=>	'Þu anki kullanýcý sayýsý: %d'
);
?>
