<?
// Login mesajlarý
$lang_msg["login"] = array(
	51	=>	'E-mail Adresiniz',
	52	=>	'Þifreniz',
	53	=>	'Login',
	54	=>	'Sisteme tekrar baðlanmak için þifrenizi giriniz.',
	55	=>	'Kullanýcý deðiþtir',
	56	=>	'Güvenli baðlantý (SSL)',
	57	=>	'Normal baðlantý',
	58	=>	'Lütfen tüm kýsýmlarý doldurunuz.',
	59	=>	'Lütfen e-mail adresinizi doðru giriniz',
	60	=>	'Lütfen þifrenizi giriniz.',
	61	=>	'Hatalý þifre ya da böyle bir e-mail adresi tanýmlý deðil.',
	62	=>	'Alan adý deðiþtir'
);
?>
