<?
// Mesaj okuma mesajlarý
$lang_msg["msgs"] = array(
	251	=>	'Kimden',
	252	=>	'Kime',
	253	=>	'Cc',
	254	=>	'Konu',
	255	=>	'Tarih',
	256	=>	'Mesaj Ýçeriði',
	257	=>	'Eklemeler:',
	258	=>	'<div align="center"><b>Mesajýn içeriði boþ</b></div>',
	259	=>	'Belirtilen mesaj bulunamadi, belki az önce silmiþ olabilirsiniz!',
	260	=>	'Önceki',		// unused
	261	=>	'Sonraki',		// unused
	262	=>	'Cevapla',
	263	=>	'Herkese Cevapla',
	264	=>	'Sil',
	265	=>	'Yönlendir',
	266	=>	'Mesaj bilgilerini göster',
	267	=>	'Konusuz',
	268	=>	'Adresi kaydet',
	269	=>	'HTML Formatlý Mesaj',
	270	=>	'RFC822 Mesajý',
	271	=>	'Teslimat Raporu',
	272	=>	'Salt Metin',
	273	=>	'Zenginleþtirilmiþ Salt Metin',
	274	=>	'Bilinmeyen Ekleme',
	275	=>	'Salt Metin',
	276	=>	'Uygulama',
	277	=>	'Ses Dosyasý',
	278	=>	'Resim Dosyasý',
	279	=>	'Video Dosyasý',
	280	=>	'PGP Ýmzasý',
	281	=>	'Mesajýn kendisi'
);
?>
