<?
/********************************************************
        lang/dk/contacts.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$cStrings=array(
    0=>"Kontaktpersoner",
    1=>"Tilf&oslash;j kontaktperson",
    2=>" kontaktperson",
    3=>"Navn",
    4=>"E-post",
    5=>"URL",
    6=>"Gruppe",
    7=>"Kommentar",
    8=>"Tilf&oslash;j/rediger kontaktperson",
    9=>"E-post",
    10=>"Ny meddelelse"
);

$cErrors=array(
	0=>"Listen med kontaktpersoner er tom"
);
?>
