<?
/********************************************************
        lang/dk/dates.inc
        (C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/
$lang_datetime =  array(
        "dsow" => array (
                        0 => "s&oslash;n",
                        1 => "man",
                        2 => "tir",
                        3 => "ons",
                        4 => "tor",
                        5 => "fre",
                        6 => "l&oslash;r"
                        ),
        "today" => "I dag %t",
        "lastweek" => "%w %t",
        "thisyear" => "%d/%m",
        "prevyears" => "%d/%m-%y"
);

?>
