<?
/********************************************************
        lang/dk/edit_contact.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$ecStrings=array(
        0=>"Rediger",
        1=>"Tilf&oslash;j",
        2=>" kontaktperson",
        3=>"Navn",
        4=>"E-post",
        5=>"URL",
        6=>"Gruppe",
        7=>"Kommentar",
        8=>"Hjemmetelefon",
        9=>"Arbejdstelefon",
        10=>"Mobiltelefon",
        11=>"Adresse",
        12=>"Alt. e-post",
        13=>"Slet",
        14=>"Andet"
);

$errors=array(
        0=>"Kunne ikke tilf&oslash;je kontaktperson: Databasefejl.",
        1=>"Der findes allerede en indgang med samme adresse.",
        2=>"Klik ",
        3=>"her",
        4=>" for i stedet at redigere den indgang.",
        5=>"Kontaktperson ikke fundet eller adgang n&aelig;gtet.",
        6=>"Er du sikker p&aring;, at du vil slette \"",
        7=>"\"?"
);
?>
