<?
/********************************************************
        lang/dk/edit_folders.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$efStrings=array(
        0=>"H&aring;ndtering af foldere",
        1=>"Opret ny folder",
        2=>"Opret folder: ",
        3=>"Opret",
        4=>"Slet folder",
        5=>"Slet",
        6=>"Omd&oslash;b folder",
        7=>"Omd&oslash;b"
);

$errors=array(
        0=>"Opret folder: ",
        1=>"Kunne ikke oprette folder: ",
        2=>"Slettet folder: ",
        3=>"Kunne ikke slette folder: ",
        4=>"Omd&oslash;bt folder: ",
        5=>"Kunne ikke omd&oslash;be folder: ",
        6=>"Der er kun muligt at f&aring; adgang til foldere for IMAP konti."
);
?>
