<?
/********************************************************
    lang/dk/prefs.inc
    (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

    This file is part of IlohaMail, and released under GPL.
    See COPYING, or http://www.fsf.org/copyleft/gpl.html

    Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$prefHeaderStrings = array(
                                            0=>"Pr&aelig;ferencer",
                                            1=>"Indstillinger",
                                            2=>"Farver"
                                            );
                                            
$prefsStrings = array(
                                    "0.0" => "Identitet",
                                    "0.1" => "Navn: ",
                                    "0.2" => "E-post: ",
                                    "1.0" => "International",
                                    "1.1" => "Gr&aelig;nseflade: ",
                                    "1.2" => "Tegns&aelig;t: ",
                                    "1.3" => "Tidszone: ",
                                    "2.0" => "Indstillinger for oversigter",
                                    "2.1" => "Vis op til ",
                                    "2.2" => " meddelelser",
                                    "2.3" => "Vis st&oslash;rrelse",
                                    "2.4" => "Sorter efter: ",
                                    "2.5" => "",
                                    "2.6" => "Sorteringsr&aelig;kkef&oslash;lge: ",
                                    "2.7" => "",
                                    "2.8" => "Vis oversigt over foldere",
                                    "3.0" => "Gem automatisk indstillinger",
                                    "3.1" => "Gem sendte meddelelser.",
                                    "3.2" => "Gem sendte meddelelser i folder: ",
                                    "3.3" => "",
                                    "3.4" => "T&oslash;m automatisk papirkurven",
                                    "3.5" => "Flyt slettede elementer til: ",
                                    "3.6" => "",
                                    "3.7" => "Hovedfolder: ",
                                    "3.8" => "Alternativ folder",
                                    "4.0" => "Indstillinger for visning af meddelelser",
                                    "4.1" => "Vis i ramme",
                                    "4.2" => "M&aelig;rk citater med farve",
                                    "4.3" => "Aktivering af denne indstilling kan sl&oslash;ve systemet.",
                                    "4.4" => "Konverter URL'er til links",
                                    "4.5" => "Vis HTML meddelelser",
                                    "4.6" => "Vis billeder i teksten",
                                    "5.0" => "Signatur",
                                    "5.1" => "Inds&aelig;t automatisk signatur",
                                    "5.2" => ""
                                    );

$sort_fields=array("DATE"=>"Dato", "SUBJECT"=>"Emne", "SIZE"=>"St&oslash;rrelse");
$sort_orders=array("ASC"=>"Stigende", "DESC"=>"Faldende");

$prefsButtonStrings = array( 0=> "Anvend", 1=>"OK", 2=> "Fortryd", 3=> "Oprindelig ops&aelig;tning");

$prefs_new_user = "Du logger &aring;benbart p&aring; for f&oslash;rste gang ... Velkommen<BR>";
$prefs_new_user .= "Tilpas indstillingerne og klik s&aring; p&aring; \"OK\"";
?>
