<?
/********************************************************
    lang/dk/cp.inc
    (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

    This file is part of IlohaMail, and released under GPL.
    See COPYING, or http://www.fsf.org/copyleft/gpl.html

    Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$pcStrings= array(
                            "0" => "Indtast en HTML farve for hvert komponent.",
                            "0.1" => "Brug ",
                            "0.2" => "oversigten over farvekoder",
                            "0.3" => " for at finde farvekoderne.",
                            "1.0" => "V&aelig;rkt&oslash;jslinie",
                            "2.0" => "Oversigt over foldere",
                            "3.0" => "Hovedbilledet", 
                            "4.0" => "Diverse",
                            "4.1" => "Citater: "
                            );
                            
$pcPortions = array( "Baggrund: ", "Links: ", "Tekst: ", "Fremh&aelig;v: ");

?>

