<?
/********************************************************
        lang/dk/read_message.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

    Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$rmStrings=array(
        0=>"Tilbage",
        1=>"Svar",
        2=>"Fremad",
        3=>"Fortryd slet",
        4=>"Slet",
        5=>"Flyt til",
        6=>"Dele",
        7=>"Dette er en HTML meddelelse. ",
        8=>"Klik her for at l&aelig;se den.",
        9=>"Vis den r&aring; meddelelse",
        10=>"St&oslash;rrelse",
        11=>"Marker som ul&aelig;st",
        12=>"Vis brevhovede",
        13=>"Rapporter spam",
        14=>"Svar til alle"
);
?>
