<?
/********************************************************
        lang/dk/search_errors.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

    Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$searchErrors=array(
        "field"=>"Ulovlig s&oslash;gestreng:  Ulovligt felt",
        "empty"=>"Ulovlig s&oslash;gestreng:  Tom s&oslash;gestreng",
        "date"=>"Ulovlig s&oslash;gestreng:  Dato ikke anf&oslash;rt"
);
?>
