<?
/********************************************************
        lang/dk/tool.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

    Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$toolStrings=array(
        "folders"=>"Foldere",
        "inbox"=>"Indbakke",
        "compose"=>"Ny meddelelse",
        "contacts"=>"Kontaktpersoner",
        "search"=>"S&oslash;g",
        "prefs"=>"Indstillinger",
        "logout"=>"Log ud",
        "go"=>"G&aring; til"
);
?>
