<?php
include('admin_design.php');
include('../application_config_file.php');
include('admin_auth.php');
@set_time_limit(0);
include(DIR_LANGUAGES.$language."/".FILENAME_ADMIN_FORM);
$jsfile="bulk_email.js";
include("header.php");
include(DIR_ADMIN.FILENAME_ADMIN_BULK_EMAIL_FORM);
include("footer.php");
?>