=head1 NAME

Net::LDAP::Search -- Object returned by Net::LDAP search method

=head1 SYNOPSIS

  use Net::LDAP;
  
  $mesg = $ldap->search( @search_args );
  
  @entries = $mesg->entries;

=head1 DESCRIPTION

=head1 CONSTRUCTOR

=head1 METHODS

=over 4

=item as_struct

=item count

=item entry ( INDEX )

=item entries

=item references

=item sorted ( [ ATTR ] )

=back

=head1 SEE ALSO

L<Net::LDAP>, L<Net::LDAP::Message>, L<Net::LDAP::Entry>,
L<Net::LDAP::Reference>

=head1 ACKNOWEDGEMENTS

This document is based on a document originally written by Russell Fulton
E<lt>F<r.fulton@auckland.ac.nz>E<gt>

=head1 AUTHOR

Graham Barr E<lt>F<gbarr@pobox.com>E<gt>

=head1 COPYRIGHT

Copyright (c) 1997-8 Graham Barr. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

=cut
