<?
/********************************************************
	lang/fr/compose.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings=array(
	0=>"Sujet",
	1=>"De",
	2=>"À",
	3=>"CC",
	4=>"CCi",
	5=>"Date"
);

$composeStrings=array(
	0=>"Nouveau message",
	1=>"Envoyer",
	2=>"Joindre le fichier",
	3=>"Joindre la signature",
	4=>"Joindre",
	5=>"Carnet d'adresses",
	6=>"Dissimuler les adresses",
	7=>"Corps du texte:",
	8=>"Ajouter",
	9=>"Le %d, %s a écrit:\n",
	10=>"--- Message d'origine ---\n"
);

$composeErrors=array(
	0=> "Ce message n'a aucun sujet.  Prière d'en entrer un. ",
	1=>"Le champ \"de\" est vide.  Prière de fournir votre adresse.",
	2=>"Le champ \"à\" est vide.  Prière d'entrer l'adresse du destinataire.",
	3=>"Erreur du téléchargement",
	4=>"Aucun fichier n'a été reçu.",
	5=>"Afin d'éviter l'envoi de courrier non sollicité (le spam), vous ne pouvez envoyer qu'à %1 des correspondants (%2 au total par session) toutes les %3 secondes."
);
?>
