<?
/********************************************************
	lang/fr/contacts.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"Contacts",
	1=>"Ajouter/modifier un contact",
	2=>"Contact",
	3=>"Nom",
	4=>"Courriel",
	5=>"URL",
	6=>"Groupe",
	7=>"Commentaires",
	8=>"Enregistrer",
	9=>"Courriel",
	10=>"Rédiger"
);

$cErrors=array(
	0=>"Le carnet d'adresses est vide"
);
?>
