<?
/********************************************************
	lang/fr/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime =  array(
	"dsow" => array (			
			0 => "Dim",
			1 => "Lun",
			2 => "Mar",
			3 => "Mer",
			4 => "Jeu",
			5 => "Ven",
			6 => "Sam"
			),
	"today" => "%t",
	"lastweek" => "%w %t",
	"thisyear" => "%m/%d",
	"prevyears" => "%y/%m/%d"
);

?>
