<?
/********************************************************
	lang/eng/edit_folders.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings=array(
	0=>"Gestion des dossiers",
	1=>"Ajouter un dossier",
	2=>"Créer un dossier: ",
	3=>"Ajouter",
	4=>"Supprimer un dossier",
	5=>"Supprimer",
	6=>"Renommer un dossier",
	7=>"Renommer"
);

$errors=array(
	0=>"Dossier ajouté: ",
	1=>"Incapable de créer le dossier: ",
	2=>"Dossier supprimé: ",
	3=>"Incapable de supprimer le dossier: ",
	4=>"Dossier renommé: ",
	5=>"Incapable de renommer le dossier: ",
	6=>"La gestion des dossiers n'est disponible qu'avec la protocol IMAP."
);
?>

