<?
/********************************************************
	lang/fr/edit_contact.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings=array(
	0=>"Modifier ",
	1=>"Ajouter ",
	2=>" Contact ",
	3=>"Nom  ",
	4=>"Courriel-1 ",
	5=>"URL",
	6=>"Groupe ",
	7=>"Commentaires ",
	8=>"Tél. domicile",
	9=>"--Tél. travail ",
	10=>"---Cellulaire ",
	11=>"Adresse ",
	12=>"Courriel-2 ",
	13=>"Supprimer ",
	14=>"Autre groupe "
);

$errors=array(
	0=>"Le contact n'a pas été ajouter; à cause d'une erreur de la base de données.",
	1=>"Cette adresse existe déjà dans votre carnet d'adresses.",
	2=>"Cliquer",
	3=>"ici",
	4=>" si vous voulez modifier cette entrée.",
	5=>"Le contact est introuvable ou l'accès est refusé.",
	6=>"Veuillez confirmer la suppression de  \"",
	7=>"\"?"
);
?>
