<?
/********************************************************
	lang/fr/cp.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html
********************************************************/

$pcStrings= array(
	"0" => "Veuillez entrer un code de couleur HTML dans chacune des sections.",
	"0.1" => "Se servir du ",
	"0.2" => "tableau des couleurs",
	"0.3" => " afin de fournir les bons codes de couleurs.",
	"1.0" => "Tableau des couleurs",
	"2.0" => "Liste des dossiers",
	"3.0" => "Autres écrans", 
	"4.0" => "Divers",
	"4.1" => "Citations: "
);
$pcPortions = array( "Arrière plan: ", "Lien: ", "Texte: ", "Surbrillance: ");

?>

