<?
/********************************************************
	lang/fr/prefs.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$prefHeaderStrings = array(
	0=> "Préférences",
	1=>"Générales",
	2=>"Couleurs"
	);
											
$prefsStrings = array(
	"0.0" => "Identité",
	"0.1" => "Nom: ",
	"0.2" => "Courriel: ",
	"1.0" => "Paramètres internationaux",
	"1.1" => "Langue: ",
	"1.2" => "Jeu de caractères: ",
	"1.3" => "Fuseau horaire: ",
	"2.0" => "Options de visualisation",
	"2.1" => "Afficher jusqu'à ",
	"2.2" => " items",
	"2.3" => "Afficher la taille des fichiers",
	"2.4" => "Champ du tri: ",
	"2.5" => "",
	"2.6" => "Ordre du tri: ",
	"2.7" => "",
	"2.8" => "Afficher la liste des dossiers",
	"3.0" => "Sauvegarde automatique",
	"3.1" => "Conserver les courriels envoyés.",
	"3.2"=> "Conserver les messages envoyés dans le dossier: ",
	"3.3" => "",
	"3.4" => "Vider la corbeille automatiquement",
	"3.5" => "Déplacer les messages supprimés dans le dossier: ",
	"3.6" => "",
	"3.7" => "Dossier principal (racine): ",
	"3.8" => "Autre chemin",
	"4.0" => "Options pour l'affichage des messages",
	"4.1" => "Visualiser dans un cadre",
	"4.2" => "Mettre les citations en couleur",
	"4.3" => "Il se peut que cette option ralentisse votre système.",
	"4.4" => "Convertir les URLs en liens",
	"4.5" => "Afficher les messages HTML",
	"4.6" => "Inclure l'affichage des images",
	"5.0" => "Signature",
	"5.1" => "Afficher la signature par défaut.",
	"5.2" => ""
	);


$sort_fields=array("DATE"=>"Date", "SUBJECT"=>"Sujet", "SIZE"=>"Taille");
$sort_orders=array("ASC"=>"Croissant", "DESC"=>"Décroissant");

$prefsButtonStrings = array( 0=> "Mettre à jour", 1=>"Enregistrer", 2=> "Défaire", 3=> 
"Valeurs par défaut");

$prefs_new_user = "C'est votre première visite ? Bienvenue !<br>";
$prefs_new_user .= "Prière de remplir ce formulaire et cliquer sur \"Enregistrer\"";
?>
