<?
/********************************************************
	lang/fr/read_message.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"Précédent",
	1=>"Répondre",
	2=>"Transmettre",
	3=>"Récupérer",
	4=>"Supprimer",
	5=>"Transférer",
	6=>"Pièces jointes",
	7=>"Ceci est un message au format HTM. ",
	8=>"Cliquer ici pour le lire.",
	9=>"Source",
	10=>"Taille",
	11=>"Marquer non lu",
	12=>"Afficher l'entête",
	13=>"Signaler le Spam",
	14=>"Répondre à tous"
);
?>
