<?
/********************************************************
	lang/fr/search_errors.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors=array(
	"field"=>"Critère de recherche non valide:  champ non valide",
	"empty"=>"Critère de recherche non valide:  chaîne des critères de recherche vide",
	"date"=>"Critère de recherche non valide:   aucune date n'a été entrée"
);
?>
