<?
/********************************************************
	lang/nl/compose.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings=array(
	0=>"Onderwerp",
	1=>"Van",
	2=>"Aan",
	3=>"CC",
	4=>"BCC",
	5=>"Datum"
);

$composeStrings=array(
	0=>"Nieuw bericht",
	1=>"Verstuur bericht",
	2=>"Voeg toe",
	3=>"Voeg handtekening toe",
	4=>"Bijvoegen",
	5=>"Toon adressenlijst",
	6=>"Verberg adressenlijst",
	7=>"Bericht tekst:",
	8=>"Voeg toe",
	9=>"Op %d schreef %s:\n",
	10=>"--- Oorspronkelijke  boodschap ---\n",
    11=>"Sluit venster"
);

$composeErrors=array(
	0=>"Het onderwerpveld is leeg. Vul alsjeblieft een onderwerp in.",
	1=>"Het \"Van\" veld is leeg. Vul alsjeblieft je e-mail adres in.",
	2=>"Het \"Aan\" veld is leeg. Vul alsjeblieft een e-mail adres in.",
	3=>"Upload mislukt.",
	4=>"Geen bestanden ontvangen.",
	5=>"Om \"spam\" tegen te gaan kan je slechts eens in de %3 seconden berichten sturen naar %1 mensen (%2 in totaal per sessie)."
);
?>