<?
/********************************************************
	lang/nl/contacts.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"Adressen",
	1=>"Voeg een adres toe",
	2=>"Contact",
	3=>"Naam",
	4=>"E-mail",
	5=>"Homepage",
	6=>"Groep",
	7=>"Extra",
	8=>"Werk gegevens bij",
	9=>"E-mail",
    10=>"Nieuw bericht"
);

$cErrors=array(
	0=>"Adressenlijst is leeg"
);
?>