<?
/********************************************************
	lang/nl/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$lang_datetime =  array(
	"dsow" => array (			
			0 => "Zon",
			1 => "Maa",
			2 => "Din",
			3 => "Woe",
			4 => "Don",
			5 => "Vri",
			6 => "Zat"
			),
	"today" => "%t",
	"lastweek" => "%w %t",
	"thisyear" => "%d/%m",
	"prevyears" => "%d/%m/%y"
);

?>