<?
/********************************************************
	lang/nl/edit_folders.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	
	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html
********************************************************/


$efStrings=array(
	0=>"Beheer mappen",
	1=>"Maak een nieuwe map",
	2=>"Nieuwe map: ",
	3=>"Maken",
	4=>"Verwijder map",
	5=>"Verwijderen",
	6=>"Hernoem map",
	7=>"Hernoemen"
);

$errors=array(
	0=>"Nieuwe map aangemaakt: ",
	1=>"Kon de map niet aanmaken: ",
	2=>"Map verwijderd: ",
	3=>"Kon de map niet verwijderen: ",
	4=>"Hernoemde map: ",
	5=>"Kon de map niet hernoemen: ",
	6=>"Map-ondersteuning is alleen beschikbaar als je IMAP gebruikt."
);

?>