<?
/********************************************************
	lang/nl/edit_contact.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings=array(
	0=>"Wijzig",
	1=>"Voeg toe",
	2=>"Adresgegevens",
	3=>"Naam",
	4=>"E-mail",
	5=>"Internet",
	6=>"Groep",
	7=>"Extra's",
	8=>"Telefoon thuis",
	9=>"Telefoon werk",
	10=>"GSM",
	11=>"Adres",
	12=>"2de e-mail",
	13=>"Verwijder",
	14=>"Anders:"
);

$errors=array(
	0=>"Kon de gegevens niet toevoegen vanwege een database fout.",
	1=>"Dat adres zit al in je adresboek.",
	2=>"Klik ",
	3=>"hier",
	4=>" om dat adres aan te passen.",
	5=>"Geen adres gevonden, of ik kon geen toegang krijgen.",
	6=>"Weet je zeker dat je het adres \"",
	7=>"\" wilt verwijderen ?"
);
?>