<?/********************************************************
	lang/nl/cp.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	
	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html
	
********************************************************/

$pcStrings= array(
    "0" => "Vul een HTML kleurkode in voor elk onderdeel.",
    	"0.1" => "Gebruik deze ",
	"0.2" => "kleurkode kaart",
	"0.3" => " om de juiste kleurkodes te vinden.",
    "1.0" => "Werkbalk",
    "2.0" => "Mappen lijst",
    "3.0" => "Hoofdscherm",
    "4.0" => "Overig",
    	"4.1" => "Citaten: "
);							

$pcPortions = array( "Achtergrond: ", "Links: ", "Tekst: ", "Geaccentueerd: ");
?>