<?
/********************************************************
	lang/nl/read_message.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"Terug",
	1=>"Beantwoorden",
	2=>"Doorsturen",
	3=>"Herstellen",
	4=>"Verwijderen",
	5=>"Verplaats",
	6=>"Onderdelen",
	7=>"Dit is een HTML bericht. ",
	8=>"Klik hier om het te lezen.",
	9=>"Bron",
	10=>"Omvang",
	11=>"Markeer als ongelezen",
	12=>"Toon header",
	13=>"Rapporteer \"spam\"",
	14=>"Iedereen beantwoorden"
);
?>