<?
/********************************************************
	lang/nl/search_errors.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors=array(
	"field"=>"Ongeldige zoekcriteria: ongeldig veld",
	"empty"=>"Ongeldige zoekcriteria: lege zoek string",
	"date"=>"Ongeldige zoekcriteria: geen datum opgegeven"
);
?>