<?
/********************************************************
	lang/nl/tool.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings=array(
	"folders"=>"Mappen",
	"inbox"=>"Inbox",
	"compose"=>"Nieuw bericht",
	"contacts"=>"Adressen",
	"search"=>"Zoek",
	"prefs"=>"Opties",
	"logout"=>"Afmelden",
	"go"=>"Ga"
);
?>