<?
//////////////////////////////////////////////////////////////////////////////
// Program Name         : Max-eMail Elite                                   //
// Release Version      : 3.01                                              //
// Program Author       : SiteOptions inc.                                  //
// Supplied by          : CyKuH [WTN]                                       //
// Nullified by         : CyKuH [WTN]                                       //
// Distribution         : via WebForum, ForumRU and associated file dumps   //
//////////////////////////////////////////////////////////////////////////////
// COPYRIGHT NOTICE                                                         //
// (c) 2002 WTN Team,  All Rights Reserved.                                 //
// Distributed under the licencing agreement located in wtn_release.nfo     //
//////////////////////////////////////////////////////////////////////////////
include "../config.inc.php";


if($action){
			if(CanPerformAction("$action|links|$LinksGroupID")!=1){

				$FULL_OUTPUT=MakeBox("ERROR OCCURED!",HandleError("Error402",2));
				FinishOutput();
			}
	//now go to the relevant section of the script to execute the desired objectives!
	switch($action){
		case "edit":
		EditLinks();
		break;
		
		case "groups";
		LinkGroups();
		break;
		
		case "report":
		LinkReport();
		break;
			
	}
}else{
	LinksMain();
}

/////////////////////////////////////////////////////////////

function LinkReport(){
	GLOBAL $FULL_OUTPUT, $LinkGroupID, $LinkID, $Links;
			
			$group=mysql_fetch_array(mysql_query("SELECT * FROM link_groups WHERE LinkGroupID='$LinkGroupID'"));
		
		if($Links){
			//we have selected the links now generate the report!
			foreach($Links as $Link){
				$li=mysql_fetch_array(mysql_query("SELECT * FROM links WHERE LinkID='$Link'"));
				$TR='Report for "'.$li[LinkName].'". Generated by Max-eMail V3 Elite on '.PrintableDate(time()).'.<P>';
				$TR.='URL: '.$li[Link].'<BR>';
				$TR.='Total Clicks: '.mysql_num_rows(mysql_query("SELECT * FROM link_clicks WHERE LinkID='$Link'")).'<BR>';
				$TR.='Total Clicks (Unique IP): ';
				$cip=mysql_query("SELECT * FROM link_clicks WHERE LinkID='$Link'");
					while($ip=mysql_fetch_array($cip)){
						$uniqueip[$ip[IPAddress]]='yes';
						$tracedby[$ip[TracedBy]][$ip[TraceCode]]++;
					}
				$TR.=count($uniqueip).'<BR>';
				
				//now print out the trace codes that have been used!
					if($tracedby){
					$traceid=array("list"=>"List", "email"=>"Users Email", "unique"=>"Users Unique Key");
					$TR.='<P><B>Tracing Information..</B><BR>';
					foreach($tracedby as $id=>$trace){
						$TR.='<P><B><I><U>Tracing by '.$traceid[$id].'</U></I></B>
						<TABLE width=80%><tr><td><span class="admintext">Trace Code</span></td><td><span class="admintext">Frequency</span></td></tr><tr height="1" bgcolor="#cccccc"><td colspan="2"></td></tr>';
					foreach($trace as $TraceCode=>$times){
						$TR.='<tr><td><span class="admintext">'.$TraceCode.'</span></td><td><span class="admintext">'.$times.'</span></td></tr>';
					}
					$TR.='</TABLE>';
					}}
				$BO.=$TR.'<P><hr size="1"><P>';
			}
			$BO.='<P>'.MakeLink("links.php?action=edit&LinkGroupID=$LinkGroupID", "Back to group main");
			$FULL_OUTPUT.=MakeBox("Link reports", $BO);
			
		}else{
			$BO.="Please select which links in the group you want a report on!<P>";
			$BO.='<table width=40%>';
			
			$links=mysql_query("SELECT * FROM links WHERE LinkGroupID='$LinkGroupID'");
				$f=0;while($l=mysql_fetch_array($links)){
					$f--;
					if($l[LinkID]==$LinkID){$sel="CHECKED";}else{$sel="";}
					$FORM_ITEMS[$f]="checkbox|Links[".$l[LinkID]."]:".$l[LinkID].":".$l[LinkName].":$sel";
				}
				$FORM_ITEMS[($f-1)]="submit|Generate Report";
				//make the form
				$FORM=new AdminForm;
				$FORM->title="LinkReports";
				$FORM->items=$FORM_ITEMS;
				$FORM->action="links.php?action=report&LinkGroupID=$LinkGroupID";
				$FORM->MakeForm();
				$BO.=$FORM->output;
				
			$FULL_OUTPUT.=MakeBox("Select report links!", $BO);
		}
}

/////////////////////////////////////////////////////////////

function LinkGroups(){
	GLOBAL $FULL_OUTPUT, $LinkGroupName, $add, $LinkGroupID, $MaximumLinks, $delete;
	
	if($delete){
		mysql_query("DELETE FROM link_groups WHERE LinkGroupID='$LinkGroupID'");
		$li=mysql_query("SELECT * FROM links WHERE LinkGroupID='$LinkGroupID'");
			while($l=mysql_fetch_array($li)){
				mysql_query("DELETE FROM link_clicks WHERE LinkID='".$l[LinkID]."'");
			}
		mysql_query("DELETE FROM links WHERE LinkGroupID='$LinkGroupID'");
		LinksMain();
		FinishOutput();
	}	
	
	if($add){
		//we are adding a link group!
		mysql_query("INSERT INTO link_groups SET LinkGroupName='$LinkGroupName', MaximumLinks='100'");
		$LinkGroupID=mysql_insert_id();
	}else{
		mysql_query("UPDATE link_groups SET LinkGroupName='$LinkGroupName', MaximumLinks='$MaximumLinks' WHERE LinkGroupID='$LinkGroupID'");
	}
	EditLinks();
	
}

/////////////////////////////////////////////////////////////

function EditLinks(){
	GLOBAL $FULL_OUTPUT, $LinkGroupID, $LinkName, $create, $LinkID, $delete, $TraceBy, $URL;
	
	$g=mysql_fetch_array(mysql_query("SELECT * FROM link_groups WHERE LinkGroupID='$LinkGroupID'"));
	
	if($create && $LinkName){
		//add a new link!
		if($g[MaximumLinks]>mysql_num_rows(mysql_query("SELECT * FROM links WHERE LinkGroupID='$LinkGroupID'"))){
			mysql_query("INSERT INTO links SET LinkGroupID='$LinkGroupID', LinkName='$LinkName', Link='http://www.'");
			$LinkID=mysql_insert_id();
		}else{
			$FULL_OUTPUT.=MakeBox("Sorry maximum links in group reached!", "The limit on number of links in this group will be exceeded if this link is added!");
		}
	}
	
	if($LinkName && $URL){
			if($TraceBy=="email"){
				$TraceCode='%LISTFIELD:x-email%';
			}elseif($TraceBy=="unique"){
				$TraceCode='%LISTFIELD:x-unique%';	
			}elseif($TraceBy=="list"){
				$TraceCode='%LISTFIELD:x-listname%';	
			}
		mysql_query("UPDATE links SET Link='$URL', LinkName='$LinkName', TraceBy='$TraceBy', TraceCode='$TraceCode' WHERE LinkID='$LinkID' && LinkGroupID='$LinkGroupID'");
		$LinkID='';
	}
	
	//are we wanting to delete a link!
	if($delete){
		mysql_query("DELETE FROM links WHERE LinkGroupID='$LinkGroupID' && LinkID='$LinkID'");
		mysql_query("DELETE FROM link_clicks WHERE LinkID='$LinkID'");
		$LinkID='';
	}
	
	//if there is a link id print the edit link form!
	if($LinkID){
	$link=mysql_fetch_array(mysql_query("SELECT * FROM links WHERE LinkID='$LinkID' && LinkGroupID='$LinkGroupID'"));
			$FORM_ITEMS["Link name"]="textfield|LinkName:30:30:".$link[LinkName];
			$FORM_ITEMS["Link URL"]="textfield|URL:1000:60:".str_replace(":", '$$COLON$$', $link[Link]);
			$FORM_ITEMS["Trace Method"]="select|TraceBy:1:none->None;list->List Name;email->Users Email;unique->Users Unique Key:".$link[TraceBy];
			$FORM_ITEMS[-1]="submit|Save Changes";
				//make the form
				$FORM=new AdminForm;
				$FORM->title="EditLink";
				$FORM->items=$FORM_ITEMS;
				$FORM->action="links.php?action=edit&LinkGroupID=$LinkGroupID&LinkID=$LinkID";
				$FORM->MakeForm();
				
				$FULL_OUTPUT.=MakeBox("Edit link", $FORM->output.'<P>'.MakeLink("links.php?action=edit&LinkGroupID=$LinkGroupID", "Back to group main"));
				FinishOutput();
	}
	
	//print a group summary box!
	$num_links=mysql_num_rows(mysql_query("SELECT * FROM links WHERE LinkGroupID='$LinkGroupID'"));
	$FULL_OUTPUT.=MakeBox("Summary of link group", "This link group currently has $num_links links. It has a link limit of ".$g[MaximumLinks]." links.<P>".MakeLink("links.php", "Back to links main"));
	
	//print the list of links in this group!
		$BO.='<TABLE width="100%"><TR><TD><span class="admintext">Link Name</span></TD><TD><span class="admintext">URL</span></TD><TD><span class="admintext">Options</span></TD></TR>
		<TR height="1" bgcolor="#cccccc"><td colspan="3"></td></TR>';
	$links=mysql_query("SELECT * FROM links WHERE LinkGroupID='$LinkGroupID' ORDER BY LinkName");
		while($l=mysql_fetch_array($links)){
			$flink=$l[Link];
				if(strlen($l[Link])>45){
					$l[Link]=substr($l[Link],0,43)."...";
				}
			$BO.='<TR><TD><span class="admintext">'.$l[LinkName].'</span></TD><TD><span class="admintext">'.MakeLink($flink, $l[Link]).'</span></TD><TD><span class="admintext">';
					$BO.=MakeLink("links.php?action=edit&LinkGroupID=$LinkGroupID&LinkID=".$l[LinkID], "Edit")." | ";
					$BO.=MakeLink("links.php?action=edit&delete=yes&LinkGroupID=$LinkGroupID&LinkID=".$l[LinkID], "Delete",1);
					if(CanPerformAction("edit|links|".$lg[LinkGroupID])==1){
						$BO.=" | ".MakeLink("links.php?action=report&LinkGroupID=$LinkGroupID&LinkID=".$l[LinkID], "Report");	
					}
				$BO.='</span></TD></TR>';
		}
		$BO.='</TABLE>';
		$FULL_OUTPUT.=MakeBox("Links in this group", $BO);
	
	//print an add link box!
				$FORM_ITEMS["Link name"]="textfield|LinkName:30:30:NewLink";
			$FORM_ITEMS[-1]="submit|Add Link";
				//make the form
				$FORM=new AdminForm;
				$FORM->title="AddLink";
				$FORM->items=$FORM_ITEMS;
				$FORM->action="links.php?action=edit&LinkGroupID=$LinkGroupID&create=yes";
				$FORM->MakeForm();
				
				$FULL_OUTPUT.=MakeBox("Add a link to this group", $FORM->output);
				
	//edit link group!
		if(CanPerformAction("groups|links|")){
			$FORM_ITEMS2["Link Group Name"]="textfield|LinkGroupName:30:30:".$g[LinkGroupName];
			$FORM_ITEMS2["MaximumLinks"]="textfield|MaximumLinks:10:10:".$g[MaximumLinks];			
			$FORM_ITEMS2[-1]="submit|Save Changes";
				//make the form
				$FORM2=new AdminForm;
				$FORM2->title="AddLinkGroup";
				$FORM2->items=$FORM_ITEMS2;
				$FORM2->action="links.php?action=groups&LinkGroupID=$LinkGroupID";
				$FORM2->MakeForm();
				
				$FULL_OUTPUT.=MakeBox("Edit link group", $FORM2->output.'<P>'.MakeLink("links.php?action=groups&LinkGroupID=$LinkGroupID&delete=yes", "Delete link group",1));
		}

}

/////////////////////////////////////////////////////////////

function LinksMain(){
	GLOBAL $FULL_OUTPUT;
	
	//edit the links in a group!
	$link_groups=mysql_query("SELECT * FROM link_groups");
	while($lg=mysql_fetch_array($link_groups)){
		if(CanPerformAction("edit|links|".$lg[LinkGroupID])==1){
			$allgroups.=$lg[LinkGroupID]."->".$lg[LinkGroupName].";";
		}
	}
	
			$FORM_ITEMS["Link Group"]="select|LinkGroupID:1:$allgroups";
			$FORM_ITEMS[-1]="submit|Edit Groups Links";
				//make the form
				$FORM=new AdminForm;
				$FORM->title="ManageLinkGroup";
				$FORM->items=$FORM_ITEMS;
				$FORM->action="links.php?action=edit";
				$FORM->MakeForm();
				
				$FULL_OUTPUT.=MakeBox("Edit a link group", $FORM->output);
	
	//add link group!
		if(CanPerformAction("groups|links|")){
			$FORM_ITEMS2["Link Group Name"]="textfield|LinkGroupName:30:30:NewLinkGroup";
			$FORM_ITEMS2[-1]="submit|Add Link Group";
				//make the form
				$FORM2=new AdminForm;
				$FORM2->title="AddLinkGroup";
				$FORM2->items=$FORM_ITEMS2;
				$FORM2->action="links.php?action=groups&add=yes";
				$FORM2->MakeForm();
				
				$FULL_OUTPUT.=MakeBox("Add a link group", $FORM2->output);
		}
	
}

/////////////////////////////////////////////////////////////


FinishOutput();

?>