<HTML>
 <HEAD>
  <!-- $MVD$:app("MicroVision WebExpress","769") -->
  <!-- $MVD$:template("","0","0") -->
  <!-- $MVD$:color("15","95bf","Brown","1") -->
  <!-- $MVD$:color("18","ff3e3e","blue blue","1") -->
  <!-- $MVD$:color("19","aeffff","baje","1") -->
  <!-- $MVD$:color("20","e18344","bblue","1") -->
  <!-- $MVD$:color("21","42d0ff","idoogleyellow","1") -->
  <!-- $MVD$:color("22","e3e3e3","Lt Grey2","1") -->
  <!-- $MVD$:color("23","b3aaf0","Lt red","1") -->
  <!-- $MVD$:color("24","80ff","halloworange","1") -->
  <!-- $MVD$:color("25","552b00","dadablue","1") -->
  <!-- $MVD$:color("26","c08000","greyblue","1") -->
  <!-- $MVD$:color("27","f1c4a5","lighterblue","1") -->
  <!-- $MVD$:color("28","df987d","lavblue","1") -->
  <!-- $MVD$:color("29","241700","fade2","1") -->
  <!-- $MVD$:color("30","4b3201","fade3","1") -->
  <!-- $MVD$:color("31","694501","fade4","1") -->
  <!-- $MVD$:color("32","8a5a02","fade5","1") -->
  <!-- $MVD$:color("33","b67703","fade6","1") -->
  <!-- $MVD$:color("34","cf8803","fade7","1") -->
  <!-- $MVD$:color("35","f19e03","fade8","1") -->
  <!-- $MVD$:color("36","fcb530","fade9","1") -->
  <!-- $MVD$:color("37","fdc660","fade10","1") -->
  <!-- $MVD$:color("38","fdd284","fade11","1") -->
  <!-- $MVD$:color("39","fedd9e","fade12","1") -->
  <!-- $MVD$:color("40","fee9c2","fade13","1") -->
  <!-- $MVD$:color("41","feefd3","fade14","1") -->
  <!-- $MVD$:color("42","f5ebde","fade15","1") -->
  <!-- $MVD$:color("43","eeffff","baje2","1") -->
  <!-- $MVD$:color("44","fff9ec","realltblue","1") -->
  <!-- $MVD$:color("45","333333","coolgrey","1") -->
  <!-- $MVD$:color("46","cc99","grape green","1") -->
  <!-- $MVD$:color("47","dce5e5","Grey Baje","1") -->
  <!-- $MVD$:color("48","996666","Custom #1","0") -->
  <!-- $MVD$:color("49","cc9999","Custom #2","0") -->
  <!-- $MVD$:color("50","5e4746","real drk purple","1") -->
  <!-- $MVD$:color("51","d6d6d6","Custom #3","0") -->
  <!-- $MVD$:color("52","bebebe","Custom #4","0") -->
  <!-- $MVD$:color("53","2a211e","Custom #5","0") -->
  <!-- $MVD$:color("54","99","Custom #6","0") -->
  <!-- $MVD$:color("55","0","fade1","1") -->
  <!-- $MVD$:color("56","ffffff","fade16","1") -->
  <!-- $MVD$:fontset("Untitled Font Set 2","Arial") -->
  <!-- $MVD$:fontset("Untitled Font Set 1","Verdana") -->
  <!-- $MVD$:fontset("Sans Serif","Arial","Helvetica","Monaco") -->
  <!-- $MVD$:fontset("Verdana","Verdana","Arial","Times New I2") -->
  <TITLE>A v i d  [News]&reg; v1.0 - Administration Panel</TITLE>
  <META NAME="GENERATOR" CONTENT="MicroVision Development / WebExpress">
 <LINK REL="stylesheet" HREF="style.css" TYPE="text/css"><STYLE>
 
 
 
 
 
 
 
 
 
 
 
 
  body {margin: 0px 0px 0px 0px;}
</STYLE>
 </HEAD>
 <BODY BGCOLOR="WHITE" LINK="#00007F" VLINK="#00007F" ALINK="#00007F">
  <P>
   <TABLE WIDTH="100%" CELLPADDING="0" CELLSPACING="0" BORDER="0">
    <TR>
     <TD WIDTH="50%" BGCOLOR="BLACK" VALIGN=BOTTOM>
      <P>
       <TABLE WIDTH="100%" CELLPADDING="2" CELLSPACING="0" BORDER="0">
        <TR>
         <TD WIDTH="12%" VALIGN=TOP></TD>
        </TR>
       </TABLE></TD>
     <TD WIDTH="50%" BGCOLOR="BLACK" VALIGN=BOTTOM>
      <P ALIGN=RIGHT>
       <IMG SRC="images/adminlogo.gif" WIDTH="221" HEIGHT="61" VSPACE="0" HSPACE="0" BORDER="0" LOOP="0"></TD>
    </TR>
   </TABLE>
   <TABLE WIDTH="100%" CELLPADDING="0" CELLSPACING="0" BORDER="0">
    <TR>
     <TD WIDTH="26%" BGCOLOR="#D6D6D6" VALIGN=TOP>
      <P>
       <TABLE WIDTH="100%" CELLPADDING="2" CELLSPACING="0" BORDER="0">
        <TR>
         <TD WIDTH="100%" BGCOLOR="#666699" VALIGN=TOP>
          <P>
           <TABLE WIDTH="100%" CELLPADDING="2" CELLSPACING="0" BORDER="0">
            <TR>
             <TD WIDTH="100%" VALIGN=TOP>
              <P ALIGN=LEFT>
               <FONT COLOR="#9999CC"><FONT FACE="Arial,Helvetica,Monaco"><FONT SIZE="4">PLEASE
                LOGIN</FONT></FONT></FONT><BR>
               <HR ALIGN=LEFT WIDTH="100%" SIZE="1" NOSHADE COLOR="#9999CC">
               <FONT FACE="Arial,Helvetica,Monaco"><FONT SIZE="2"><FONT COLOR="WHITE"><A HREF="admin.php?action=news" CLASS="subnav1"><BR>
               </A></FONT></FONT></FONT></P>
              <P>
               <!-- $MVD$:spaceretainer() -->&nbsp;</P>
              <P>
               <!-- $MVD$:spaceretainer() -->&nbsp;</P>
              <P>
               <!-- $MVD$:spaceretainer() -->&nbsp;</P>
              <P>
               <!-- $MVD$:spaceretainer() -->&nbsp;</P>
              <P>
               <!-- $MVD$:spaceretainer() -->&nbsp;</TD>
            </TR>
           </TABLE></TD>
        </TR>
        <TR>
         <TD WIDTH="100%" BGCOLOR="#D6D6D6" VALIGN=TOP>
          <P>
           <!-- $MVD$:spaceretainer() -->&nbsp;</P>
          <P>
           <!-- $MVD$:spaceretainer() -->&nbsp;</P>
          <P>
           <!-- $MVD$:spaceretainer() -->&nbsp;</P>
          <P>
           <!-- $MVD$:spaceretainer() -->&nbsp;</P>
          <P>
           <!-- $MVD$:spaceretainer() -->&nbsp;</P>
          <P>
           <!-- $MVD$:spaceretainer() -->&nbsp;</P>
          <P>
           <!-- $MVD$:spaceretainer() -->&nbsp;</P>
          <P ALIGN=CENTER>
           <FONT SIZE="1"><FONT FACE="Arial,Helvetica,Monaco"><FONT COLOR="#666699">&copy;
            2003 AvidNewMedia. [WDYL]</FONT></FONT></FONT><BR>
           <FONT SIZE="1"><FONT FACE="Arial,Helvetica,Monaco"><FONT COLOR="#666699">All
            Rights Reserved.</FONT></FONT></FONT></TD>
        </TR>
       </TABLE></TD>
     <TD WIDTH="74%" VALIGN=TOP>
      <P>
       <TABLE WIDTH="100%" CELLPADDING="5" CELLSPACING="0" BORDER="0">
        <TR>
         <TD WIDTH="100%" VALIGN=TOP BACKGROUND="images/adminbgheader.gif" STYLE="background-repeat: no-repeat;">
          <P>
           <!-- $MVD$:spaceretainer() -->&nbsp;</P>
          <P>
           <!-- $MVD$:spaceretainer() -->&nbsp;</P>
          <P>
           <!-- $MVD$:spaceretainer() -->&nbsp;</P>
          <P>