CREATE TABLE mp3 (
id tinyint(4) NOT NULL auto_increment,
text1 text NOT NULL,
link1 text NOT NULL,
text2 text NOT NULL,
link2 text NOT NULL,
text3 text NOT NULL,
link3 text NOT NULL,
text4 text NOT NULL,
link4 text NOT NULL,
text5 text NOT NULL,
link5 text NOT NULL,
text6 text NOT NULL,
link6 text NOT NULL,
text7 text NOT NULL,
link7 text NOT NULL,
text8 text NOT NULL,
link8 text NOT NULL,
text9 text NOT NULL,
link9 text NOT NULL,
text10 text NOT NULL,
link10 text NOT NULL,
date text NOT NULL,
img text NOT NULL,
artist text NOT NULL,
artistabc text NOT NULL,
album text NOT NULL,
PRIMARY KEY (id)
) TYPE=MyISAM; 
