<?php

//----------------------------
// german language include file
//----------------------------

// message list screen

$L_MESSAGE		= "Nachricht";
$L_MESSAGES 		= "Nachrichten";
$L_FOLDER_SWITCH	= "wechsel zum Ordner";
$L_FOLDER_MOVE		= "verschiebe markierte Nachrichten nach";
$L_SELECT_ERROR		= "Bitte zuerst eine Nachricht markieren";

// folder list screen

$L_FOLDERS		= "Ordner";
$L_FOLDER_CREATE	= "erstelle einen Ordner";
$L_FOLDER_DELETE	= "l&ouml;sche den Ordner";
$L_NAMED		= "Name";

// message compose

$L_MESSAGE_COMPOSE	= "Nachricht erstellen";

// headers

$L_SUBJECT_HDR		= "Betreff";
$L_FROM_HDR		= "Von";
$L_RECEIVED_HDR		= "Empfangen";
$L_SIZE_HDR		= "Gr&ouml;sse";
$L_TO_HDR		= "Nach";
$L_CC_HDR		= "Kopie";
$L_FILE_HDR		= "Datei";
$L_DATE_HDR		= "Datum";
$L_FILES_HDR		= "Dateien";
$L_FOLDER_NAME		= "Ordner-Name";
$L_NUM_MESSAGES		= "Nachrichten";

// buttons

$L_FOLDER_BTN		= "Ordner";
$L_DELETE_BTN		= "L&ouml;sche";
$L_COMPOSE_BTN		= "erstelle";
$L_LOGOUT_BTN		= "Login";
$L_REPLY_BTN		= "Antworten";
$L_REPLYALL_BTN		= "Allen Antworten";
$L_FORWARD_BTN		= "Weiterleiten";
$L_SEND_BTN		= "Senden";
$L_GO_BACK_BTN		= "zur&uuml;ck";
$L_SUBMIT_BTN		= "los";

// misc

$L_NO_SUBJECT		= "[kein Betreff]";
$L_NO_TO		= "Kein Empf&auml;nger eingetragen";
$L_NO_FROM		= "Kein Sender eingetragen";
$L_MIME_SECTION		= "Section";
$L_IMAGE		= "Bild";
$L_ORIG_MSG		= "---- Original Nachricht ----";
$L_FOLDER_EMPTY		= "Dieser Ordner ist leer";

?>