<?php

//----------------------------
// english language include file
//----------------------------

// message list screen

$L_MESSAGE		= "message";
$L_MESSAGES 		= "messages";
$L_FOLDER_SWITCH	= "switch current folder to";
$L_FOLDER_MOVE		= "move selected messages into";
$L_SELECT_ERROR		= "Please select a message first.";

// folder list screen

$L_FOLDERS		= "Folders";
$L_FOLDER_CREATE	= "create a folder";
$L_FOLDER_DELETE	= "delete the folder";
$L_NAMED		= "named";

// message compose

$L_MESSAGE_COMPOSE	= "Message Compose";

// headers

$L_SUBJECT_HDR		= "Subject";
$L_FROM_HDR		= "From";
$L_SENT_HDR		= "Sent";
$L_RECEIVED_HDR		= "Received";
$L_SIZE_HDR		= "Size";
$L_TO_HDR		= "To";
$L_CC_HDR		= "Cc";
$L_FILE_HDR		= "File";
$L_DATE_HDR		= "Date";
$L_FILES_HDR		= "Files";
$L_FOLDER_NAME		= "Folder Name";
$L_NUM_MESSAGES		= "Messages";

// buttons

$L_FOLDER_BTN		= "Folders";
$L_DELETE_BTN		= "Delete";
$L_COMPOSE_BTN		= "Compose";
$L_LOGOUT_BTN		= "Login";
$L_REPLY_BTN		= "Reply";
$L_REPLYALL_BTN		= "Reply All";
$L_FORWARD_BTN		= "Forward";
$L_SEND_BTN		= "Send";
$L_GO_BACK_BTN		= "Go Back";
$L_SUBMIT_BTN		= "Go";

// misc

$L_NO_SUBJECT		= "[No Subject]";
$L_NO_TO		= "Undisclosed Recipients";
$L_NO_FROM		= "Undisclosed Sender";
$L_MIME_SECTION		= "Section";
$L_IMAGE		= "Image";
$L_ORIG_MSG		= "---- Original Message ----";
$L_FOLDER_EMPTY		= "This folder is empty";

?>
