<?php

//----------------------------
// spanish language include file
// by pastito@dd.com.ar
//----------------------------

// message list screen

$L_MESSAGE		= "mensaje";
$L_MESSAGES 		= "mensajes";
$L_FOLDER_SWITCH	= "cambiar de la carpeta actual a";
$L_FOLDER_MOVE		= "mover mensajes seleccionados a";
$L_SELECT_ERROR		= "Por favor primero seleccione un mensaje.";

// folder list screen

$L_FOLDERS		= "Carpetas";
$L_FOLDER_CREATE	= "crear una carpeta";
$L_FOLDER_DELETE	= "borrar una carpeta";
$L_NAMED		= "nombre";

// message compose

$L_MESSAGE_COMPOSE	= "Escribir mensaje";

// headers

$L_SUBJECT_HDR		= "Tema";
$L_FROM_HDR		= "De";
$L_RECEIVED_HDR		= "Recibido";
$L_SIZE_HDR		= "Tama&ntilde;o";
$L_TO_HDR		= "Para";
$L_CC_HDR		= "Cc";
$L_FILE_HDR		= "Archivo";
$L_DATE_HDR		= "Fecha";
$L_FILES_HDR		= "Archivos";
$L_FOLDER_NAME		= "Nombre carpeta";
$L_NUM_MESSAGES		= "Mensajes";

// buttons

$L_FOLDER_BTN		= "Carpetas";
$L_DELETE_BTN		= "Borrar";
$L_COMPOSE_BTN		= "Componer";
$L_LOGOUT_BTN		= "(Re)Ingreso";
$L_REPLY_BTN		= "Responder";
$L_REPLYALL_BTN		= "Responder todos";
$L_FORWARD_BTN		= "Redirigir";
$L_SEND_BTN		= "Enviar";
$L_GO_BACK_BTN		= "Volver";
$L_SUBMIT_BTN		= "OK";

// misc

$L_NO_SUBJECT		= "[No hay tema]";
$L_NO_TO		= "Receptor oculto";
$L_NO_FROM		= "Remitente oculto";
$L_MIME_SECTION		= "Secci&oacute;n";
$L_IMAGE		= "Im&aacute;gen";
$L_ORIG_MSG		= "---- Mensaje original ----";
$L_FOLDER_EMPTY		= "Esta carpeta est&aacute; vac&iacute;a";

?>