<?php

//----------------------------
// french language include file
//----------------------------

// message list screen

$L_MESSAGE		= "message";
$L_MESSAGES 		= "messages";
$L_FOLDER_SWITCH	= "sélectionner le dossier";
$L_FOLDER_MOVE		= "déplacer le message sélectionné dans";
$L_SELECT_ERROR		= "Veuillez d'abord sélectionner un message";

// folder list screen

$L_FOLDERS		= "Dossiers";
$L_FOLDER_CREATE	= "créer un dossier";
$L_FOLDER_DELETE	= "effacer le dossier";
$L_NAMED		= "nommé";

// message compose

$L_MESSAGE_COMPOSE	= "Ecrire un message";

// headers

$L_SUBJECT_HDR		= "Sujet";
$L_FROM_HDR		= "De";
$L_RECEIVED_HDR		= "Recu";
$L_SIZE_HDR		= "Taille";
$L_TO_HDR		= "A";
$L_CC_HDR		= "Cc";
$L_FILE_HDR		= "Fichier";
$L_DATE_HDR		= "Date";
$L_FILES_HDR		= "Fichiers";
$L_FOLDER_NAME		= "Nom du dossier";
$L_NUM_MESSAGES		= "Messages";

// buttons

$L_FOLDER_BTN		= "Dossiers";
$L_DELETE_BTN		= "Effacer";
$L_COMPOSE_BTN		= "Ecrire";
$L_LOGOUT_BTN		= "Logout";
$L_REPLY_BTN		= "Répondre";
$L_REPLYALL_BTN		= "Répondre à tous";
$L_FORWARD_BTN		= "Faire suivre";
$L_SEND_BTN		= "Envoyer";
$L_GO_BACK_BTN		= "Retour";
$L_SUBMIT_BTN		= "Envoyer";

// misc

$L_NO_SUBJECT		= "[Pas de sujet]";
$L_NO_TO		= "Récipients cachés";
$L_NO_FROM		= "Envoyeur anonyme";
$L_MIME_SECTION		= "Section";
$L_IMAGE		= "Image";
$L_ORIG_MSG		= "---- Message original ----";
$L_FOLDER_EMPTY		= "Ce dossier est vide";

?>
