<?php

//--------------------------------
// hungarian language include file
//--------------------------------

// message list screen

$L_MESSAGE		= "levél";
$L_MESSAGES 		= "levél";
$L_FOLDER_SWITCH	= "váltás a következõ mappára";
$L_FOLDER_MOVE		= "kijelölt levelek mozgatása a következõ mappába";
$L_SELECT_ERROR		= "Kérem jelöljön ki elõbb egy levelet.";

// folder list screen

$L_FOLDERS		= "Mappák";
$L_FOLDER_CREATE	= "mappa létrehozása";
$L_FOLDER_DELETE	= "mappa törlése";
$L_NAMED		= "neve:";

// message compose

$L_MESSAGE_COMPOSE	= "levél írása";

// headers

$L_SUBJECT_HDR		= "Tárgy";
$L_FROM_HDR		= "Feladó";
$L_RECEIVED_HDR		= "Érkezett";
$L_SIZE_HDR		= "Méret";
$L_TO_HDR		= "Címzett";
$L_CC_HDR		= "Másolat";
$L_FILE_HDR		= "Fájl";
$L_DATE_HDR		= "Dátum";
$L_FILES_HDR		= "Fájlok";
$L_FOLDER_NAME		= "Mappa neve";
$L_NUM_MESSAGES		= "Levelek száma";

// buttons

$L_FOLDER_BTN		= "Mappák";
$L_DELETE_BTN		= "Törlés";
$L_COMPOSE_BTN		= "Levél írása";
$L_LOGOUT_BTN		= "Kilépés";
$L_REFRESH_BTN		= "Frissítés";
$L_REPLY_BTN		= "Válasz";
$L_REPLYALL_BTN		= "Válasz mindenkinek";
$L_FORWARD_BTN		= "Továbbítás";
$L_SEND_BTN		= "Küldés";
$L_GO_BACK_BTN		= "Vissza";
$L_SUBMIT_BTN		= "Végrehajt";

// misc

$L_NO_SUBJECT		= "[Nincs tárgy]";
$L_NO_TO		= "Rejtett címzett";
$L_NO_FROM		= "Rejtett feladó";
$L_MIME_SECTION		= "Rész";
$L_IMAGE		= "Kép";
$L_ORIG_MSG		= "---- Eredeti levél ----";
$L_FOLDER_EMPTY		= "Ez a mappa üres";

?>