<?
/********************************************************
	lang/cn/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"地址簿",
	1=>"新建联系人",
	2=>" 联系人",
	3=>"姓名",
	4=>"Email 邮箱",
	5=>"网站网址",
	6=>"所属群组",
	7=>"附加说明",
	8=>"新建/编辑联系人",
	9=>"寄信",
    10=>"写信"
);

$cErrors=array(
	0=>"您的地址簿当前没有任何数据。"
);

?>
