<?
/********************************************************
	lang/cn/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings=array(
	0=>"编辑",
	1=>"新建",
	2=>" 联系人",
	3=>"姓名",
	4=>"Email 邮箱",
	5=>"网站网址",
	6=>"所属群组",
	7=>"附加说明",
	8=>"电话（家）",
	9=>"电话（公）",
	10=>"行动电话",
	11=>"通讯地址",
	12=>"Email 邮箱 2",
	13=>"删除",
	14=>"其他"
);

$errors=array(
	0=>"无法新建联系人：数据库发生错误。",
	1=>"地址簿里已经有该联系人的数据了。",
	2=>"点选",
	3=>"这里",
	4=>"可以编辑该联系人",
	5=>"未找到该联系人，或不能访问。",
	6=>"您确实要删除“",
	7=>"”吗？"
);
?>
