<?
/********************************************************
	lang/cn/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings=array(
	0=>"信件箱管理",
	1=>"新建信件箱",
	2=>"新建信件箱：",
	3=>"新建",
	4=>"删除信件箱",
	5=>"删除",
	6=>"信件箱重命名",
	7=>"重命名"
);

$errors=array(
	0=>"新建信件箱：",
	1=>"无法新建此信件箱：",
	2=>"删除信件箱：",
	3=>"无法删除此信件箱：",
	4=>"信件箱重命名：",
	5=>"无法更改此信件箱的名称：",
	6=>"自定义信件箱功能仅提供 IMAP 帐号使用。"
);
?>
