<?
/********************************************************
	lang/cn/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings= array(
							"0" => "请填入颜色代码值来设置各项颜色。",
							"0.1" => "请使用",
							"0.2" => "颜色代码表",
							"0.3" => "来查询并设置合适的颜色。",
							"1.0" => "工具栏",
							"2.0" => "信件箱列表",
							"3.0" => "主窗口", 
							"4.0" => "杂项设置",
							"4.1" => "引用："
							);
							
$pcPortions = array( "背景颜色：", "链接颜色：", "文字颜色：", "高亮度显示颜色：");

?>
