<?
/********************************************************
	lang/cn/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"返回",
	1=>"回信",
	2=>"转发",
	3=>"取消删除",
	4=>"删除",
	5=>"文件",
	6=>"附加部分",
	7=>"这是一封 HTML 格式邮件。",
	8=>"点选这里可以立即读取。",
	9=>"邮件原始码",
	10=>"大小",
	11=>"标记未读",
	12=>"显示邮件标头",
	13=>"回报垃圾邮件",
	14=>"回信给所有人"
);
?>
