<?
/********************************************************
	lang/cn/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings=array(
	"folders"=>"信件箱一览",
	"inbox"=>"收件匣",
	"compose"=>"写信",
	"contacts"=>"地址簿管理",
	"search"=>"查找邮件",
	"prefs"=>"首选",
	"logout"=>"注销",
	"go"=>"Go"
);
?>
