<?
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"Contatos",
	1=>"Adicionar Contato",
	2=>" Contato",
	3=>"Nome",
	4=>"Email",
	5=>"URL",
	6=>"Grupo",
	7=>"Coment&aacute;rios",
	8=>"Adicionar/Editar Contato",
	9=>"Email",
    10=>"Comp&ocirc;r"
);

$cErrors=array(
	0=>"A lista de contatos est&aacute; vazia"
);

?>
