<?
/********************************************************
	lang/eng/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime =  array(
	"dsow" => array (			
			0 => "Dom",
			1 => "Seg",
			2 => "Ter",
			3 => "Qua",
			4 => "Qui",
			5 => "Sex",
			6 => "Sab"
			),
	"today" => "Hoje %t",
	"lastweek" => "%w %t",
	"thisyear" => "%m/%d",
	"prevyears" => "%m/%d/%y"
);

?>
