<?
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings=array(
	0=>"Gerenciar Pastas",
	1=>"Criar nova pasta",
	2=>"Criar pasta: ",
	3=>"Criar",
	4=>"Excluir pasta",
	5=>"Excluir",
	6=>"Renomear pasta",
	7=>"Renomear"
);

$errors=array(
	0=>"Criar pasta: ",
	1=>"Imposs&iacute;vel criar pasta: ",
	2=>"Pasta excluida: ",
	3=>"Imposs&iacure;vel excluir pasta: ",
	4=>"Pasta renomeada: ",
	5=>"Imposs&iacute;vel renomear pasta: ",
	6=>"Suporte a pasta est&aacute; dispon&iacute;vel apenas para contas do tipo IMAP."
);
?>
