<?
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings=array(
	0=>"Editar",
	1=>"Adicionar",
	2=>" Contato",
	3=>"Nome",
	4=>"Email",
	5=>"URL",
	6=>"Grupo",
	7=>"Coment&aacute;rios",
	8=>"Telefone casa",
	9=>"Telefone trabalho",
	10=>"Telefone celular",
	11=>"Endere&ccedil;o",
	12=>"Email alternativo",
	13=>"Excluir",
	14=>"Outros"
);

$errors=array(
	0=>"Imposs&iacute;vel adicionar contato:  erro no banco de dados.",
	1=>"Um registro com o endere&ccedil;o j&aacute; existe.",
	2=>"Clique ",
	3=>"aqui",
	4=>" para editar esse registro.",
	5=>"Contato n&atilde;o encontrato ou acesso n&atilde;o permitido.",
	6=>"Tem certeza de que quer excluir o registro de \"",
	7=>"\"?"
);
?>
