<?
/********************************************************
	lang/eng/prefs.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$prefHeaderStrings = array(
											0=> "Prefer&ecirc;ncias",
											1=>"Geral",
											2=>"Cores"
											);
											
$prefsStrings = array(
									"0.0" => "Identifica&ccedil;&atilde;o",
									"0.1" => "Nome: ",
									"0.2" => "Email: ",
									"1.0" => "Internacional",
									"1.1" => "Interface: ",
									"1.2" => "Conjunto de caracteres: ",
									"1.3" => "Time Zone: ",
									"2.0" => "Op&ccedil;&otilde;es de visualiza&ccedil;&atilde;o",
									"2.1" => "Mostrar at&eacute; ",
									"2.2" => " itens",
									"2.3" => "Mostrar tamanho",
									"2.4" => "Ordernar por: ",
									"2.5" => "",
									"2.6" => "Ordena&ccedil;&atilde;o: ",
									"2.7" => "",
									"2.8" => "Mostrar lista de pastas",
									"3.0" => "Op&ccedil;&otilde;es de Auto-Salvamento",
									"3.1" => "Salvar itens enviados.",
									"3.2"=> "Salvar itens enviados na pasta: ",
									"3.3" => "",
									"3.4" => "Limpar Excluidas automaticamente",
									"3.5" => "Mover itens excluidos para a pasta: ",
									"3.6" => "",
									"3.7" => "Diret&oacute;rio Raiz: ",
									"3.8" => "Outros",
									"4.0" => "Op&ccedil;&otilde;es de Visualiza&ccedil;&atilde;o de Mensagens",
									"4.1" => "Visualizar em frames",
									"4.2" => "Marcas coloridas",
									"4.3" => "Ligar essa op&ccedil;&atilde;o pode deixar o sistema lento.",
                                    "4.4" => "Converter URLs em links",
									"4.5" => "Mostrar mensagens HTML",
									"4.6" => "Mostrar imagens",
									"5.0" => "Assinatura",
									"5.1" => "Mostrar assinatura por padr&atilde;o",
									"5.2" => ""
									);

$sort_fields=array("DATE"=>"Data", "SUBJECT"=>"Assunto", "SIZE"=>"Tam");
$sort_orders=array("ASC"=>"Ascendente", "DESC"=>"Descendente");

$prefsButtonStrings = array( 0=> "Atualizar", 1=>"Aplicar", 2=> "Cancelar", 3=> "Padr&otilde;es");

$prefs_new_user = "Parece que voce est&acute; se conectando pela primeira vez... seja bem-vindo!<br>";
$prefs_new_user .= "Por favor, preencha as configura&ccedil;&otilde;es a seguir e ent&atilde;o pressione \"Aplicar\"";
?>
