<?
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"Voltar",
	1=>"Responder",
	2=>"Encaminhar",
	3=>"Reverter exclus&atilde;o",
	4=>"Excluir",
	5=>"Arquivo",
	6=>"Partes",
	7=>"Esta &eacute; uma mensagem HTML. ",
	8=>"Clique aqui para ler.",
	9=>"C&oacute;digo fonte",
	10=>"Tamanho",
	11=>"Marcar como n&atilde;o lida",
	12=>"Mostrar cabe&ccedil;alho",
	13=>"Relatar Spam",
	14=>"Responder a todos"
);
?>
