<?
/********************************************************
	lang/eng/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors=array(
	"field"=>"Crit&eacute;rio de pesquisa inv&aacute;lido:  Campo inv&aacute;lido",
	"empty"=>"Crit&eacute;rio de pesquisa inv&aacute;lido:  String de pesquisa vazio",
	"date"=>"Crit&eacute;rio de pesquisa inv&aacute;lido:  Data n&atilde;o especificada"
);
?>
