<?
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings=array(
	"folders"=>"Pastas",
	"inbox"=>"Entrada",
	"compose"=>"Nova mensagem",
	"contacts"=>"Contatos",
	"search"=>"Pesquisar",
	"prefs"=>"Op&ccedil;&otilde;es",
	"logout"=>"Desconectar",
	"go"=>"Ir"
);
?>
