Configuration(View|config_view,Backup|subscribe_backup)
Users(View|users_view,Add|users_add,Edit|users_edit,Delete|users_delete)
Newsletters(View|newsletters_view,Add|newsletters_add,Edit|newsletters_edit,Delete|newsletters_delete,Templates|newsletters_template)
Newsletter Issues(View|issues_view,Add|issues_add,Send|issues_send,Edit|issues_edit,Delete|issues_delete,Import|issues_import)
Topics(View|topics_view,Add|topics_add,Edit|topics_edit,Delete|topics_delete)
Subscribers(View|subscribe_view,Import|subscribe_import,Export|subscribe_export,Delete|subscribe_delete,Custom Fields|subscribe_custom)
Stats(View|stats_view)