<?
/********************************************************
	lang/tw/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"通訊錄",
	1=>"新增連絡人",
	2=>" 連絡人",
	3=>"姓名",
	4=>"Email 信箱",
	5=>"網站網址",
	6=>"所屬群組",
	7=>"附加說明",
	8=>"新增/編輯連絡人",
	9=>"寄信",
    10=>"寫信"
);

$cErrors=array(
	0=>"您的通訊錄目前沒有任何資料。"
);

?>