<?
/********************************************************
	lang/tw/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime =  array(
	"dsow" => array (			
			0 => "日",
			1 => "一",
			2 => "二",
			3 => "三",
			4 => "四",
			5 => "五",
			6 => "六"
			),
	"today" => "[今日] %t",
	"lastweek" => "%w %t",
	"thisyear" => "%m/%d",
	"prevyears" => "%y/%m/%d"
);

?>