<?
/********************************************************
	lang/tw/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings=array(
	0=>"信件匣管理",
	1=>"新增信件匣",
	2=>"新增信件匣：",
	3=>"新增",
	4=>"刪除信件匣",
	5=>"刪除",
	6=>"信件匣更名",
	7=>"更名"
);

$errors=array(
	0=>"新增信件匣：",
	1=>"無法新增此信件匣：",
	2=>"刪除信件匣：",
	3=>"無法刪除此信件匣：",
	4=>"信件匣更名：",
	5=>"無法更改此信件匣的名稱：",
	6=>"自訂信件匣功能僅提供 IMAP 帳號使用。"
);
?>