<?
/********************************************************
	lang/tw/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings=array(
	0=>"編輯",
	1=>"新增",
	2=>" 連絡人",
	3=>"姓名",
	4=>"Email 信箱",
	5=>"網站網址",
	6=>"所屬群組",
	7=>"附加說明",
	8=>"電話（家）",
	9=>"電話（公）",
	10=>"行動電話",
	11=>"通訊地址",
	12=>"Email 信箱 2",
	13=>"刪除",
	14=>"其他"
);

$errors=array(
	0=>"無法新增連絡人：資料庫發生錯誤。",
	1=>"通訊錄裡已經有該連絡人的資料了。",
	2=>"點選",
	3=>"這裡",
	4=>"可以編輯該連絡人",
	5=>"找不到該連絡人，或無法存取。",
	6=>"您確定要刪除「",
	7=>"」嗎？"
);
?>