<?
/********************************************************
	lang/tw/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"返回",
	1=>"回信",
	2=>"轉信",
	3=>"取消刪除",
	4=>"刪除",
	5=>"檔案",
	6=>"附加部分",
	7=>"這是一封 HTML 格式信件。",
	8=>"點選這裡可以立即讀取。",
	9=>"信件原始碼",
	10=>"大小",
	11=>"標記未讀",
	12=>"顯示信件標頭",
	13=>"回報垃圾信件",
	14=>"回信給所有人"
);
?>