<?
/********************************************************
	lang/tw/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings=array(
	"folders"=>"信件匣一覽",
	"inbox"=>"收件匣",
	"compose"=>"寫信",
	"contacts"=>"通訊錄管理",
	"search"=>"搜尋信件",
	"prefs"=>"偏好設定",
	"logout"=>"登出",
	"go"=>"Go"
);
?>