<?
/********************************************************
	lang/pl/contacts.inc
	(C) 2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"Ksi±¿ka Adresowa",
	1=>"Dodaj Osobê",
	2=>" Ksi±¿ka Adresowa",
	3=>"Imiê",
	4=>"Email",
	5=>"URL",
	6=>"Grupa",
	7=>"Komentarze",
	8=>"Dodaj/Edytuj Wpis",
	9=>"Email",
    	10=>"Nowa Wiadomo¶æ"
);

$cErrors=array(
	0=>"Lista kontaktów jest pusta"
);

?>