<?
/********************************************************
	lang/pl/dates.inc
	(C) 2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime =  array(
	"dsow" => array (			
			0 => "Nd",
			1 => "Pn",
			2 => "Wt",
			3 => "Œr",
			4 => "Czw",
			5 => "Pt",
			6 => "So"
			),
	"today" => "Dzisiaj %t",
	"lastweek" => "%w %t",
	"thisyear" => "%d/%m",
	"prevyears" => "%d/%m/%y"
);

?>