<?
/********************************************************
	lang/pl/edit_folders.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings=array(
	0=>"Zarz±dzanie folderami",
	1=>"Utwórz nowy folder",
	2=>"Utwórz folder: ",
	3=>"Utwórz",
	4=>"Usuñ folder",
	5=>"Usuñ",
	6=>"Zmieñ nazwê folderu",
	7=>"Rename"
);

$errors=array(
	0=>"Utwórzono folder: ",
	1=>"Nie mo¿na utworzyæ folderu: ",
	2=>"Usuniêto folder: ",
	3=>"Nie mo¿na usun±æ folderu: ",
	4=>"Zmieniono nazwê folderu: ",
	5=>"Nie mo¿na zmieniæ nazwy folderu: ",
	6=>"Obs³uga folderów jest dostêpna tylko dla protoko³u IMAP."
);
?>