<?
/********************************************************
	lang/pl/edit_contact.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings=array(
	0=>"Edytuj",
	1=>"Dodaj",
	2=>" Ksi±¿ka adresowa",
	3=>"Imiê",
	4=>"Email",
	5=>"URL",
	6=>"Grupa",
	7=>"Komentarze",
	8=>"Tel. Domowy",
	9=>"Tel. S³u¿bowy",
	10=>"Tel. Komórkowy",
	11=>"Adres",
	12=>"Drugi Email",
	13=>"Usuñ",
	14=>"Inne"
);

$errors=array(
	0=>"Nie mogê dodaæ wpisu:  b³±d bazy danych.",
	1=>"Istnieje ju¿ wpis o podanym adresie.",
	2=>"Naciœnij ",
	3=>"tutaj",
	4=>" by modyfikowaæ wpis.",
	5=>"Osoba nie zosta³a odnaleziona, lub brak dostêpu.",
	6=>"Czy na pewno chcesz usun±æ wpis dla \"",
	7=>"\"?"
);
?>