<?
/********************************************************
	lang/pl/cp.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings= array(
							"0" => "Dla ka¿dego elementu wprowad¼ kod koloru HTML.",
							"0.1" => "U¿yj ",
							"0.2" => "Tabeli Kolorów",
							"0.3" => " by znale¼æ w³a¶ciwe kody kolorów.",
							"1.0" => "Pasek Narzêdziowy",
							"2.0" => "Lista Folderów",
							"3.0" => "G³ówne", 
							"4.0" => "Ró¿ne",
							"4.1" => "Cytaty: "
							);
							
$pcPortions = array( "T³o: ", "Odno¶niki: ", "Tekst: ", "Pod¶wietlenie: ");

?>
