<?
/********************************************************
	lang/pl/prefs.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$prefHeaderStrings = array(
											0=>"Ustawienia",
											1=>"Ogólne",
											2=>"Kolory"
											);
											
$prefsStrings = array(
									"0.0" => "To¿samo¶æ",
									"0.1" => "Imiê: ",
									"0.2" => "Email: ",
									"1.0" => "Miedzynarodowe",
									"1.1" => "Interfejs: ",
									"1.2" => "Zestaw Znaków: ",
									"1.3" => "Strefa Czasowa: ",
									"2.0" => "Opcje Wy¶wietlania Listy",
									"2.1" => "Pokazuj do ",
									"2.2" => " obiektów",
									"2.3" => "Poka¿ rozmiar",
									"2.4" => "Sortuj wed³ug: ",
									"2.5" => "",
									"2.6" => "Porz±dek sortowania: ",
									"2.7" => "",
									"2.8" => "Poka¿ listê folderów",
									"3.0" => "Opcje Autozapisu",
									"3.1" => "Zachowuj wys³ane wiadomo¶ci.",
									"3.2"=> "Zachowuj wiadomo¶ci wys³ane w folderze: ",
									"3.3" => "",
									"3.4" => "Automatycznie opró¿niaj kosz",
									"3.5" => "Przeno¶ skasowane listy do folderu: ",
									"3.6" => "",
									"3.7" => "Glówny Katalog: ",
									"3.8" => "Inne",
									"4.0" => "Opcje Wy¶wietlania Wiadomo¶ci",
									"4.1" => "Ogl±daj w ramce",
									"4.2" => "Koloruj cytaty",
									"4.3" => "W³±czenie tej opcji mo¿e spowolnic pracê systemu.",
                                    					"4.4" => "Zamieniaj adresy URL na odno¶niki",
									"4.5" => "Pokazuj wiadomo¶ci HTML",
									"4.6" => "Wklejaj obrazki",
									"5.0" => "Sygnatura",
									"5.1" => "Domy¶lne wstawianie sygnatury",
									"5.2" => ""
									);

$sort_fields=array("DATE"=>"Data", "SUBJECT"=>"Temat", "SIZE"=>"Rozmiar");
$sort_orders=array("ASC"=>"Rosn±co", "DESC"=>"Malej±co");

$prefsButtonStrings = array( 0=> "Aktualizuj", 1=>"Zastosuj", 2=> "Anuluj", 3=> "Domy¶lne");

$prefs_new_user = "Wygl±da na to, ¿e logujesz sie po raz pierwszy...witaj!<br>";
$prefs_new_user .= "Proszê dokonaæ nastêpuj±cych ustawieñ, potem nacisn±æ \"Zastosuj\"";
?>