<?
/********************************************************
	lang/pl/read_message.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"Poprzednia",
	1=>"Odpowiedz",
	2=>"Prze¶lij",
	3=>"Przywróc",
	4=>"Usuñ",
	5=>"Plik",
	6=>"Cze¶ci",
	7=>"To jest wiadomo¶æ HTML. ",
	8=>"Naci¶nij tu by j± przeczytaæ.",
	9=>"¬ród³o",
	10=>"Rozmiar",
	11=>"Oznacz Jako Nieczytan±",
	12=>"Poka¿ Nag³ówek",
	13=>"Poinformuj o Spamie",
	14=>"Odpowiedz Wszystkim"
);
?>