<?
/********************************************************
	lang/pl/search_errors.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors=array(
	"field"=>"Bledne kryterium wyszukiwawcze:  B³êdne pole",
	"empty"=>"B³êdne kryterium wyszukiwawcze:  Puste pole wyszukiwania",
	"date"=>"B³êdne kryterium wyszukiwawcze:  Nieokre¶lona data"
);
?>