<?
/********************************************************
	lang/pl/tool.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings=array(
	"folders"=>"Katalogi",
	"inbox"=>"Skrzynka odbiorcza",
	"compose"=>"Nowa wiadomo¶æ",
	"contacts"=>"Ksi±¿ka adresowa",
	"search"=>"Szukaj",
	"prefs"=>"Ustawienia",
	"logout"=>"Wyloguj",
	"go"=>"Id¼"
);
?>