#!/usr/bin/perl
#--------------------------------------------------------------
#  "tBOSS" 1.86 php rerank test				      
#--------------------------------------------------------------
#                    DO NOT EDIT THIS FILE                    
#--------------------------------------------------------------

package cronrerank;
require "/path_to_liblog/cgi-bin/liblog.cgi";

libLog::logAction("cron rerank");
system("./genlist.cgi");