<html><head><title>hotddls - Hot Direct Downloads - Disclaimer</title><table cellspacing=0 cellpadding=0 border=0 width=594 class=dl id=bb>
<tr><th width=100% id=t><div id=d>Disclaimer:</div></th></tr>
<tr><td height="761" style="padding:5px;">Before you contact our <a href="admin@hotddls.com">legal department</a>, please be aware of the following... 
<p align="left">HotDDLs does not host ANY software! This site merely indexes other sites' contents. We are not responsible for anything you may download, and we do not support software piracy what-so-ever. In fact we are against it and encourage our surfers to purchase retail copies of any given software link found on the web. We are also against P2P piracy and will give our full support to the aid of any anti-piracy group. </p>
<p align="left">HotDDLs Downloads is an automated script consisted of URLs submitted by webmasters. While the administrators and moderators of this site will attempt to remove or edit any generally objectionable material as quickly as possible, it is impossible to review every post. Therefore you acknowledge that all posts made to this site express the views and opinions of the author and not the administrators, moderators or webmaster (except for posts by these people) and hence take no responsibility for these page's contents, as covered in Chapter 5, part 512/513, Title 17 of the United States Code. </p>
<p align="left">&sect; 512. Limitations on liability relating to material online (a) Transitory Digital Network Communications.-A service provider shall not be liable for monetary relief, or, except as provided in subsection (j), for injunctive or other equitable relief, for infringement of copyright by reason of the provider's transmitting, routing, or providing connections for, material through a system or network controlled or operated by or for the service provider, or by reason of the intermediate and transient storage of that material in the course of such transmitting, routing, or providing connections, if- (1) the transmission of the material was initiated by or at the direction of a person other than the service provider;</p>
<p align="left">(2) the transmission, routing, provision of connections, or storage is carried out through an automatic technical process without selection of the material by the service provider; </p>
<p align="left">(3) the service provider does not select the recipients of the material except as an automatic response to the request of another person; (4) no copy of the material made by the service provider in the course of such intermediate or transient storage is maintained on the system or network in a manner ordinarily accessible to anyone other than anticipated recipients, and no such copy is maintained on the system or network in a manner ordinarily accessible to such anticipated recipients for a longer period than is reasonably necessary for the transmission, routing, or provision of connections; and (5) the material is transmitted through the system or network without modification of its content. </p>
<p align="left">&sect; 513. Determination of reasonable license fees for individual proprietors In the case of any performing rights society subject to a consent decree which provides for the determination of reasonable license rates or fees to be charged by the performing rights society, notwithstanding the provisions of that consent decree, an individual proprietor who owns or operates fewer than 7 non-publicly traded establishments in which nondramatic musical works are performed publicly and who claims that any license agreement offered by that performing rights society is unreasonable in its license rate or fee as to that individual proprietor, shall be entitled to determination of a reasonable license rate or fee as follows:</p>
<p align="left">(1) The individual proprietor may commence such proceeding for determination of a reasonable license rate or fee by filing an application in the applicable district court under paragraph (2) that a rate disagreement exists and by serving a copy of the application on the performing rights society. Such proceeding shall commence in the applicable district court within 90 days after the service of such copy, except that such 90-day requirement shall be subject to the administrative requirements of the court.</p>
<p align="left">(2) The proceeding under paragraph (1) shall be held, at the individual proprietor's election, in the judicial district of the district court with jurisdiction over the applicable consent decree or in that place of holding court of a district court that is the seat of the Federal circuit (other than the Court of Appeals for the Federal Circuit) in which the proprietor's establishment is located.</p>
<p align="left">(3) Such proceeding shall be held before the judge of the court with jurisdiction over the consent decree governing the performing rights society. At the discretion of the court, the proceeding shall be held before a special master or magistrate judge appointed by such judge. Should that consent decree provide for the appointment of an advisor or advisors to the court for any purpose, any such advisor shall be the special master so named by the court.</p>
<p align="left">(4) In any such proceeding, the industry rate shall be presumed to have been reasonable at the time it was agreed to or determined by the court. Such presumption shall in no way affect a determination of whether the rate is being correctly applied to the individual proprietor.</p>
<p align="left">(5) Pending the completion of such proceeding, the individual proprietor shall have the right to perform publicly the copyrighted musical compositions in the repertoire of the performing rights society by paying an interim license rate or fee into an interest bearing escrow account with the clerk of the court, subject to retroactive adjustment when a final rate or fee has been determined, in an amount equal to the industry rate, or, in the absence of an industry rate, the amount of the most recent license rate or fee agreed to by the parties. (6) Any decision rendered in such proceeding by a special master or magistrate judge named under paragraph (3) shall be reviewed by the judge of the court with jurisdiction over the consent decree governing the performing rights society. Such proceeding, including such review, shall be concluded within 6 months after its commencement. (7) Any such final determination shall be binding only as to the individual proprietor commencing the proceeding, and shall not be applicable to any other proprietor or any other performing rights society, and the performing rights society shall be relieved of any obligation of nondiscrimination among similarly situated music users that may be imposed by the consent decree governing its operations. (8) An individual proprietor may not bring more than one proceeding provided for in this section for the determination of a reasonable license rate or fee under any license agreement with respect to any one performing rights society.</p>
<p align="left">For controversial reasons, if you enter this site with the intent to harm any person(s) associated with HotDDLs Downloads, you must leave now. You are forbidden to enter this site. This site is a Transitory Digital Network intended for private users only, simply for educational purposes. If you do continue, you are not agreeing to these terms and you are violating code 431.322.12 of the Internet Privacy Act signed by Bill Clinton in 1995 and that means that you CANNOT threaten or harm our ISP(s) or any person(s) or company storing this site, and cannot prosecute any person(s) affiliated with this domain which includes family, friends or individuals who run or enter this web site. </p>
<p align="left">By continuing, you are expressly and impliedly agreeing to all terms as stated above, and affirm that you are in compliance with all federal, state and local laws concerning the content of this site. By going any further into hotddls.com, you Agree to all of the above, otherwise you must leave this web site immediately.</p>
<p align="left">For purposes of this section, the term &quot;industry rate&quot; means the license fee a performing rights society has agreed to with, or which has been determined by the court for, a significant segment of the music user industry to which the individual proprietor belongs.</p></TD>
</tr></table><br><div style="text-align:center;"><span>&copy; 2005 HotDDLs</span></div></td></tr></table></body></html>