<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'N&atilde;o sei onde procurar. Por favor tente novamente',
	602	=>	'N&atilde;o sei o que procurar. Por favor tente novamente.',
	603	=>	'Por favor seja mais espec&iacute;fico',
	604	=>	'Nada encontrado. Por favor tente novamente.',
	605	=>	'A busca encontrou %d mensagens.',
	606	=>	'Pode-se procurar um determinado texto dentro das mensagens. Pode-se procurar nos trechos <u>Remetente</u>, <u>assunto</u> and <u>corpo</u> da mensagem. Selecione as caixa postais a serem vasculhadas, digite o texto e aperte o bot&atilde;o <b>Procurar</b>.<br><br>A busca <b>n&atilde;o</b> &eacute; sens&iacute;vel ao caixa e se mais de uma palavra for digitada, somente as mensagens que contiverem todas as palavras ser&aacute;o mostradas.',
	607	=>	'Corpo',
	608	=>	'Assunto',
	609	=>	'Remetente',
	610	=>	'<not used>',
	611	=>	'Procurar',
	612	=>	'As caixas postais n&atilde;o foram especificadas.',
	613	=>	'Data'
);
?>
