<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Sim',
	2	=>	'N&atilde;o',
	3	=>	'Escolha',
	4	=>	'O javascript deve estar habilitado para o webmail ser eficiente',
	5	=>	'O CSS deve estar habilitado para o webmail ser eficiente',
	6	=>	'O Cookie deve estar habilitado para o webmail ser eficiente',
	7	=>	'Desconhecido',
	8	=>	'Imprimir',
	9	=>	'Fechar a janela',
	10	=>	'N&uacute;mero atual de usu&aacute;rios: %d'
);
?>
