<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Seu endere&ccedil;o Eletr&ocirc;nico',
	52	=>	'Senha',
	53	=>	'Login',
	54	=>	'Por favor digite sua senha para acessar',
	55	=>	'Mudar o usu&aacute;rio',
	56	=>	'Conex&atilde;o segura (pode ser mais demorado)',
	57	=>	'Conex&atilde;o insegura',
	58	=>	'Por favor preencha todos os campos.',
	59	=>	'Por favor informe seu endere&ccedil;o eletr&ocirc;nico corretamente.',
	60	=>	'Sua senha.',
	61	=>	'Senha ou endere&ccedil;o eletr&ocirc;nico inv&aacute;lido.',
	62	=>	'Change domain'
);
?>
