<?
// Messages related with reading a message
$lang_msg["msgs"] = array(
	251	=>	'Remetente',
	252	=>	'Destinat&aacute;rio',
	253	=>	'Cc',
	254	=>	'Assunto',
	255	=>	'Data',
	256	=>	'Corpo da mensagem',
	257	=>	'Anexos:',
	258	=>	'<div align="center"><b>Corpo da mensagem vazio</b></div>',
	259	=>	'A mensagem selecionada n&atilde;o p&ocirc;de ser mostrada!',
	260	=>	'Anterior',		// unused
	261	=>	'Seguinte',		// unused
	262	=>	'Responder',
	263	=>	'Responder para todos',
	264	=>	'Apagar',
	265	=>	'Redirecionar',
	266	=>	'Mostrar cabe&ccedil;alho',
	267	=>	'Sem assunto',
	268	=>	'Salvar endere&ccedil;o',
	269	=>	'Mensagem formatada em HTML',
	270	=>	'Mensagem formato RFC822',
	271	=>	'Status de envio',
	272	=>	'Mensagem texto puro',
	273	=>	'Mensagem "Enriched Text"',
	274	=>	'Anexo desconhecido',
	275	=>	'Mensagem texto',
	276	=>	'Aplica&ccedil;&atilde;o',
	277	=>	'Arquivo de audio',
	278	=>	'Imagem',
	279	=>	'Video',
	280	=>	'Assinatura PGP',
	281	=>	'Message Body'
);
?>
