<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'Usted no especifico que desea buscar.',
	602	=>	'Usted no especifico que desea buscar.',
	603	=>	'Por favor sea mas especifico',
	604	=>	'No encontrado, intentelo nuevamente.',
	605	=>	'Su busqueda encontro %d mensajes.',
	606	=>	'Usted puede buscar mensajes en sus carpetas que contengan alguna cadena de caracteres. Usted puede hacer la busqueda por <u>Desde:</u>, <u>Asunto</u> y  <u>Cuerpo</u> partes del mensaje. Seleccione las carpetas que donde desea buscar, entre la parte del texto, y presione  <b>Buscar</b> .<br><br> Buscar<b>no</b>reconoce minusculas y mayusculas.',
	607	=>	'Cuerpo',
	608	=>	'Asunto',
	609	=>	'Desde',
	610	=>	'<not used>',
	611	=>	'Buscar',
	612	=>	'Usted no especifico en que carpetas buscar.',
	613	=>	'Fecha'
);
?>
