<?
// Global messages
$lang_msg["global"] = array(
        1       =>      'Si',
	2	=>	'No',
        3       =>      'Po favor seleccione',
        4       =>      'Usted debe tener un navegador con JAVA SCRIPT para que funcione correctamente',
        5       =>      'Usted debe tener un navegador con CSS para que funcione correctamente',
        6       =>      'Usted debe de aceptar COOKIES para que funcione correctamente',
        7       =>      'Desconocido',
        8       =>      'Imprimir',
        9       =>      'Cerrar Ventana',
        10      =>      'Hay # usuarios: %d'
);
?>
