<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Nombre de casilla',
	52	=>	'Clave',
	53	=>	'Entrar',
	54	=>	'Por favor digite su clave para entrar',
	55	=>	'Cambiar Usuario',
	56	=>	'',
	57	=>	'Conección Insegura',
	58	=>	'Favor completar todos los campos',
	59	=>	'Por favor entre su e-mail correctamente.',
	60	=>	'Por favor entre su clave.',
	61	=>	'Clave incorrecta o e-mail no encontrado.',
	62	=>	'Change domain'
);
?>
