<?
// Messages related with reading a message
$lang_msg["msgs"] = array(
	251	=>	'Desde',
	252	=>	'Para',
	253	=>	'Cc',
	254	=>	'Asunto',
	255	=>	'Fecha',
	256	=>	'Cuerpo del Mensaje',
	257	=>	'Archivos Adjuntos:',
	258	=>	'<div align="center"><b>El cuerpo del mensaje está vacío</b></div>',
	259	=>	'El mensaje especificado no puede ser encontrado, quizá ya lo haya borrado!',
	260	=>	'Prev',		// unused
	261	=>	'Next',		// unused
	262	=>	'Responder',
	263	=>	'Responder a Todos',
	264	=>	'Borrar',
	265	=>	'Re-enviar',
	266	=>	'Ver encabezado',
	267	=>	'Sin Asunto',
	268	=>	'Guardar Dirección',
	269	=>	'Mensaje en formato HTML',
	270	=>	'Mensaje RFC822',
	271	=>	'Estado del Envío',
	272	=>	'Mensaje en formato Texto',
	273	=>	'Mensaje en formato Texto',
	274	=>	'Archivo adjunto desconocido',
	275	=>	'Texto del Mensaje',
	276	=>	'Aplicación',
	277	=>	'Archivo de Audio',
	278	=>	'Archivo de Imagen',
	279	=>	'Video Clip',
	280	=>	'PGP Signature',
	281	=>	'Message Body'
);
?>
