#    Frederic Fillon
#  fillon@webstore.Fr
# http://www.webstore.fr
#Date : 27/12/2002 03:25:12
 

%LANG = (
#################################################################
# FRENCH TRANSLATION FILE
#
  home         => 'Accueil',
  login        => 'login',
  register     => 'register',
  registration => 'Registration',
  welcome      => 'bienvenue',
  callid       => 'Call ID',
  status       => 'Status',
  username     => 'Nom utilisateur',
  password     => 'Mot de passe',
  lpassword    => 'Mot de passe perdu',
  remember     => 'Se souvenir',
  maintxt      => 'Veuillez vous identifier ci-dessous ou créer un nouveau compte.',
  createacc    => 'CREER UN NOUVEAU COMPTE',
  notregistered=> 'PAS DE COMPTE?',
  submit       => 'Envoyer',
  step         => 'Step',
  step1text    => 'Veuillez choisir un nom d\'utilisateur et un mot de passe',
  step2text    => 'Veuillez renseigner les éléments suivants',
  name         => 'Nom',
  email        => 'E-mail', 
  company      => 'Société',
  mainreg      => 'Merci pour la création de votre compte utilisateur. Vous pouvez maintenant vous identifier et soumettre un ticket pour obtenir notre assistance. Souvenez-vous de votre nom d\'utilisateur et de votre mot de passe pour de future ticket. Un email vient de vous etre envoyé.  ',
  complete     => 'Completé',
  logout       => 'SORTIR',
  announcement => 'Annonces',
  reset        => 'Effacer',
  mailedpass   => 'Merci, votre nouveau mot de passe vient de vous être envoyé.',
  kb           => 'BASE DE CONNAISSANCES',
  helpdesk     => 'HELP DESK',
  search       => 'Recherche',
  query        => 'Requête',
  category     => 'Categorie',
  recarticles  => 'Articles récents',
  viewentry    => 'Voir une entrée',
  request      => 'Demande',
  subject      => 'Sujet',
  author       => 'Autheur',
  results      => 'Resultats',
  callid       => 'Ticket ID',
  status       => 'Status',
  priority     => 'Priorité',
  whenlogged   => 'Connecté le',
  comments     => 'Commentaires',
  welcome      => 'Bienvenue',
  welc1main    => 'Merci de vous être identifier sur le help desk',
  welc2main    => 'Toutes les demandes en attentes sont affichées ci-dessous',
  company      => 'Société',
  profilemain  => 'Si vous souhaitez mettre à jour vos informations, veuillez le faire ci-dessous. Le changement du mot de passe impliquera de vous ré-identifier dans la zone membre',
  profile      => 'Profile',
  profilepass  => 'Si vous souhaitez effacer votre mot de passe, veuillez le taper deux fois ci-dessous. Les changements sont immédiats et vous devrez vous ré-identifier. Si vous voulez garder votre mot de passe laissez ces zone vides.',
  lpasstext    => 'Veuillez entrer votre nom d\'utilisateur et votre adresse email, votre nouveau mot de passe sera envoyé par mail',
  searchtext   => 'Résultat de votre recherche',
  logtext1     => 'Avant de soumettre votre demande penser à vérifiez la ',
  kbsmall      => 'Base de connaissance',
  logtext2     => ' il se peut que vous y trouviez la réponse à votre demande.',
  logtext3     => 'Veuillez remplir les informations ci-dessous pour soumettre votre demande',
  logtext4     => 'Veuillez choisir le numéro de priorité correspondant à l\'urgence de votre demande.',
  urgent       => 'urgent',
  inquiry      => 'demande',
  category     => 'Categorie',
  details      => 'Details',
  logged       => 'Connecté',
  change       => 'changer',
  usfollow     => 'Utilisateur/Staff réponses',
  addtocall    => 'Ajouter à la demande',
  ulogin       => 'S\'identifier',
  submitted    => 'Enregistré',
  thankyou     => 'Merci',
  time         => 'Temps',
  enewpass     => 'Votre mot de passe a été effacé du help desk, veuillez regarder les nouvelles informations ci-dessous :',
  enewreq1     => 'Nous vous remercions de l\'envoi de votre demande d\'assistance. Veuillez trouver ci-dessous le détail de votre demande :',
  enewreq2     => 'Les utilisateurs enregistrés peuvent se sconnecter pour prendre connaissance du status de leur demande',
  erespons1    => 'a répondu à votre demande sur le help desk',
  erespons2    => 'Merci d\'utiliser le help desk, si vous aviez d\'autres difficultés ou si vous devez intervenir sur votre demande, veuillez vous identifier sur le le help desk ',
  ereg1        => 'Merci de vous être enregistré sur le help desk, lors du moindre problème n\'hésitez pas à vous identifier sur le help desk et d\'envoyer vos demandes. Un membre de notre équipe prendra en compte vos demandes dans les plus brefs délais.',
  kregards     => 'Salutations',

  inindex1     => 'Vous avez un total de',
  inindex2     => 'tickets irrésolus',
  subrec       => 'Demande reçue.',
  subrec2      => 'zone membres',      

  error1       => 'Veuiller vérifier que tous les chmaps requis sont renseignés.',
  error2       => ' existe déjà',
  error3       => 'Veuillez entrer le',
  error4       => 'Les mots de passe ne sont pas identiques',
  error5       => 'Veuillez entre votre',
  error6       => 'Compte incorrect',
  update       => 'Mise à jour',
  back         => 'Retour',
  searchall    => 'Chercher tout',

  loggedout    => 'Vous vous êtes déconnecté',
  logbackin    => 'Se ré-identifier',
  profileup    => 'Votre profile est modifié. Veuillez vous ré-identifier si vous avez changé votre mot de passe.',
  main         => 'PRINCIPAL',
  sreq         => 'DEMANDE',
  opencalls    => 'TICKETS OUVERTS',
  closedcalls  => 'TICKETS FERMES',
  editprofile  => 'EDITER LE PROFILE'
  


);
