

%LANG = (

#################################################################

# GERMAN TRANSLATION FILE

#

  home         => 'Startseite',

  login        => 'login',

  register     => 'neu registrieren',

  registration => 'Registrierung',

  welcome      => 'Willkommen',

  callid       => 'Vorgangsnummer',

  status       => 'Status',

  username     => 'Benutzername',

  password     => 'Passwort',

  lpassword    => 'Passwort vergessen',

  remember     => 'Login merken (Cookie)',

  maintxt      => 'Bitte loggen Sie sich in Ihren bestehenden Support-Account ein, oder erstellen Sie einfach einen neuen.',

  createacc    => 'NEUEN SUPPORT-ACCOUNT ERSTELLEN',

  notregistered=> 'NICHT REGISTRIERT?',

  submit       => 'abschicken',

  step         => 'Schritt',

  step1text    => 'Bitte geben Sie einen neuen Benutzernamen und ein Passwort ein.',

  step2text    => 'Bitte geben Sie die folgenden Daten ein:',

  name         => 'Name',

  email        => 'E-mail', 

  company      => 'Firma',

  mainreg      => 'Vielen Dank, dass Sie einen Support-Account erstellt haben. Sie können Sich jetzt zu jeder Zeit einloggen und eine Supportanfrage stellen. Bitte notieren

		   Sie sich Ihre Zugangsdaten. Es wurde auch eine Email gesandt an ',

  complete     => 'abgeschlossen',

  logout       => 'ABMELDEN',

  announcement => 'Ankündigung',

  reset        => 'zurückgesetzt',

  mailedpass   => 'Vielen Dank, Ihr neues Passwort wurde Ihnen per Email zugesandt',

  kb           => 'Wissensdatenbank',

  helpdesk     => 'Supportsystem',

  search       => 'suchen in der ',

  query        => 'Suchbegriff',

  category     => 'Kategorie',

  recarticles  => 'Neueste Artikel',

  viewentry    => 'Eintrag ansehen',

  request      => 'Anfrage',

  subject      => 'Betreff',

  author       => 'Autor',

  results      => 'Ergebnisse',

  callid       => 'Vorgangsnummer',

  status       => 'Status',

  priority     => 'Priorität',

  whenlogged   => 'wann erstellt',

  comments     => 'Kommentare',

  welcome      => 'Willkommen',

  welc1main    => 'Vielen Dank, dass Sie sich in unser Supportsystem eingeloggt haben.',

  welc2main    => 'Alle nicht erledigten Anfragen werden unten angezeigt.',

  company      => 'Firma',

  profilemain  => 'Wenn Sie ihre Benutzerinformationen ändern möchten, können Sie dies hier tun. Wenn Sie das Passwort ändern möchten, müssen Sie sich danach erneut einloggen.',

  profile      => 'Profile',

  profilepass  => 'Wenn Sie ihr Passwort ändern möchten, geben Sie es bitte 2 mal ein. Änderungen sind sofort wirksam und Sie müssen sich danach erneut einloggen. Wenn Sie Ihr altes Passwort behalten möchten, lassen Sie das Feld einfach leer.',

  lpasstext    => 'Bitte geben Sie den Benutzernamen und Ihre Emailadresse für Ihren Account ein, Ihr neues Passwort wird Ihnen dann umgehend per Email zugesandt',

  searchtext   => 'Ihre Suche ergab',

  logtext1     => 'Bevor Sie eine neue Supportanfrage erstellen, durchsuchen Sie bitte die ',

  kbsmall      => 'Wissendatenbank',

  logtext2     => ', weil Ihre Anfrage sich vielleicht bereits dort befindet.',

  logtext3     => 'Bitte füllen Sie alle der untenstehenden Felder aus um Ihre Anfrage zu übermitteln..',

  logtext4     => 'Bitte vergeben Sie anhand der Dringlichkeit Ihrer Anfrage eine Prioritätsnummer.',

  urgent       => 'höchst dringend',

  inquiry      => 'einfache Anfrage',

  category     => 'Kategorie',

  details      => 'Details',

  logged       => 'erstellt',

  change       => 'Änderung',

  usfollow     => 'Antworten von Kunde / Bearbeiter',

  addtocall    => 'Zum Vorgang hinzufügen',

  ulogin       => 'anmelden',

  submitted    => 'abgeschickt',

  thankyou     => 'Vielen Dank',

  time         => 'Zeit',

  enewpass     => 'Ihr Passwort im Helpdesk wurde geändert, hier sind Ihre neuen Zugangsdaten:',

  enewreq1     => 'Vielen Dank, dass Sie eine Anfrage an unseren Support gestellt haben. Eine Zusammenfassung Ihrer Anfrage sehen Sie unten:',

  enewreq2     => 'Registrierte Benutzer können Ihre Anfrage in Ihrem Account nachverfolgen',

  erespons1    => 'hat auf Ihre Supportanfrage geantwortet',

  erespons2    => 'Vielen Dank, dass Sie unseren Service genutzt haben. Sollten Sie Rückfragen oder weitere Probleme haben, können Sie uns diese gerne über das Supportsystem mitteilen.',

  ereg1        => 'Vielen Dank, dass Sie sich bei unserem Supportsystem angemeldet haben. Falls Sie irgendwann Probleme mit einem unserer Produkte haben, richten Sie einfach eine Anfrage an unseren Support.  Ein Mitarbeiter unseres Teams wird diese sobald als möglich bearbeiten.',

  kregards     => 'Mit freundlichen Grüssen,',



  inindex1     => 'Sie haben ingesamt ',

  inindex2     => 'ungelöste Anfragen',

  subrec       => 'Anfrage abgeschickt. Zurück zum',

  subrec2      => 'Mitgliedsbereich',      



  error1       => 'Bitte füllen Sie alle Felder aus.',

  error2       => ' existiert bereits.',

  error3       => 'Bitte geben Sie die',

  error4       => 'Die Passwörter sind nicht gleich.',

  error5       => 'Bitte geben Sie ihr',

  error6       => 'Fehlerhaftes Login',

  update       => 'aktualisieren',

  back         => 'zurück',

  searchall    => 'alle durchsuchen',



  loggedout    => 'Sie sind nun abgemeldet.',

  logbackin    => 'Wieder einloggen',

  profileup    => 'Ihre Daten sind nun auf dem neuesten Stand. Wenn Sie ihr Passwort geändert haben, müssen Sie sich erneut einloggen.',

  main         => 'ÜBERSICHT',

  sreq         => 'EINE NEUE ANFRAGE STELLEN',

  opencalls    => 'OFFENE ANFRAGEN',

  closedcalls  => 'ABGESCHLOSSENE ANFRAGEN',

  editprofile  => 'STAMMDATEN EDITIEREN'

  





);
