<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'Du har inte angivit var s&ouml;kning skall ske. F&ouml;rs&ouml;k igen...',
	602	=>	'Du har inte gett n&aring;got s&ouml;kbegrepp. F&ouml;rs&ouml;k igen...',
	603	=>	'Var mer specifik i s&ouml;kbegreppet.',
	604	=>	'Inget brev hittat. F&ouml;rs&ouml;k igen...',
	605	=>	'Hittade %d brev som mostvarar s&ouml;kbegreppet.',
	606	=>	'Du kan fritexts&ouml;ka bland breven i mapparna. Du kan s&ouml;ka i f&auml;lten <u>Fr&aring;n</u>, <u>&Auml;rende</u> och i <u>Meddelandetexten</u> <br><br>S&ouml;kningen &auml;r inte k&auml;nslig f&ouml;r versaler eller gemener. Om du anger flera ord betraktas dessa som en fras.',
	607	=>	'Meddelandetext',
	608	=>	'Ärende',
	609	=>	'Från',
	610	=>	'<not used>',
	611	=>	'S&ouml;k',
	612	=>	'Du har inte angivit i vilka mappar s&ouml;kningen skall g&ouml;ras.',
	613	=>	'Datum'
);
?>
