<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Ja',
	2	=>	'Nej',
	3	=>	'V&auml;lj',
	4	=>	'Din browers m&aring;ste acceptera JavaScript f&ouml;r att BasiliX skall fungera',
	5	=>	'Din browers m&aring;ste acceptera CSS f&ouml;r att BasiliX skall fungera',
	6	=>	'Din browers m&aring;ste acceptera Cookies f&ouml;r att BasiliX skall fungera',
	7	=>	'Ok&auml;nt',
	8	=>	'Skriv ut',
	9	=>	'St&auml;ng f&ouml;nstret',
	10	=>	'Antal inloggade anv&auml;ndare: %d'
);
?>
