<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Din mailadress',
	52	=>	'L&ouml;senord',
	53	=>	'Logga in',
	54	=>	'Ange l&ouml;senord f&ouml;r att logga in igen',
	55	=>	'Byt anv&auml;ndare',
	56	=>	'Byt till krypterad f&ouml;rbindelse (SSL)',
	57	=>	'Byt till okrypterad f&ouml;rbindelse',
	58	=>	'Fyll i alla f&auml;lt',
	59	=>	'Felaktigt angiven mailadress',
	60	=>	'Ange l&ouml;senord',
	61	=>	'Fel l&ouml;senord eller mailadress',
	62	=>	'Change domain'
);
?>
