<?
// Messages related with reading a message
$lang_msg["msgs"] = array(
	251	=>	'Fr&aring;n',
	252	=>	'Till',
	253	=>	'CC (kopia)',
	254	=>	'&Auml;rende',
	255	=>	'Datum',
	256	=>	'Meddelande',
	257	=>	'Bilagor:',
	258	=>	'<div align="center"><b>Brevet inneh&aring;ller ingen meddelandetext.</b></div>',
	259	=>	'Brevet g&aring;r inte att hitta. Det kan nyligen ha raderats!',
	260	=>	'F&ouml;reg.',		// unused
	261	=>	'N&auml;sta',		// unused
	262	=>	'Svara',
	263	=>	'Svara alla',
	264	=>	'Radera',
	265	=>	'Vidarebefordra',
	266	=>	'Visa mailheader',
	267	=>	'Inget &auml;rende',
	268	=>	'Spara i adressboken',
	269	=>	'HTML-formaterat brev',
	270	=>	'RFC822-brev',
	271	=>	'Leveransstatus',
	272	=>	'Enkelt textmeddelande',
	273	=>	'Ut&ouml;kat textmeddelande',
	274	=>	'Okänt format',
	275	=>	'Textmeddelande',
	276	=>	'Program',
	277	=>	'Ljudfil',
	278	=>	'Bildfil',
	279	=>	'R&ouml;rlig video',
	280	=>	'PGP Signatur',
	281	=>	'Message Body'
);
?>
