<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'Et määrittänyt mitään paikkaa mistä haetaan.',
	602	=>	'Et määrittänyt mitä tietoa haetaan.',
	603	=>	'Ole hyvä ja tarkenna hakuehtoa.',
	604	=>	'Hakuehtoa vastaavia viestejä ei löytynyt.',
	605	=>	'Hakuehtoa vastaavia viestejä löytyi %d kpl.',
	606	=>	'Voit hakea viestejä jotka sisältävät tietyn tekstin. Voit suorittaa tarkennetun haun joka rajataan <u>Lähettäjän</u>, <u>Aiheen</u> tai <u>Viestin</u> mukaan. Valitse kansiot joista viestiä haetaan, anna hakuehto ja klikkaa <b>"Hae viestit"</b>-nappia.<br><br> Haku <b>ei</b> tee eroa pienille ja isoille kirjaimille joten jos annoit enemmän kuin yhden hakuehdon, vain hakuehdot täyttävät viestit näytetään. Viestit listataan siinä järjestyksessä kuin olet antanut hakusanat.',
	607	=>	'Viesti',
	608	=>	'Aihe',
	609	=>	'Lähettäjä',
	610	=>	'<ei käytössä>',
	611	=>	'Etsi',
	612	=>	'Et valinnut yhtään kansiota mistä haetaan.',
	613	=>	'Päiväys'
);
?>
