<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Kyllä',
	2	=>	'Ei',
	3	=>	'Valitse',
	4	=>	'Sinun pitää sallia JavaScript jos haluat käyttää tehokkaasti.',
	5	=>	'Sinun pitää sallia CSS jos haluat käyttää tehokkaasti.',
	6	=>	'Sinun pitää sallia Keksituki jos haluat käyttää tehokkaasti.',
	7	=>	'Määrittelemätön',
	8	=>	'Tulosta',
	9	=>	'Sulje ikkuna',
	10	=>	'Käyttäjiä sisällä tällä hetkellä %d kpl.'
);
?>
