<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Sähköpostiosoitteesi',
	52	=>	'Salasana',
	53	=>	'Kirjaudu',
	54	=>	'Ole hyvä ja tarkista salasanasi',
	55	=>	'Vaihda käyttäjää',
	56	=>	'Salattu yhteys (voi olla hidas)',
	57	=>	'Salaamaton yhteys',
	58	=>	'Ole hyvä ja täytä kaikki kentät.',
	59	=>	'Ole hyvä ja anna sähköpostiosoite oikeassa muodossa.',
	60	=>	'Anna salasanasi.',
	61	=>	'Väärä salasana tai tuntematon käyttäjätunnus.',
	62	=>	'Change domain'
);
?>
