<?
// Messages related with reading a message
$lang_msg["msgs"] = array(
	251	=>	'Lähettäjä',
	252	=>	'Vastaanottaja',
	253	=>	'Kopio',
	254	=>	'Aihe',
	255	=>	'Päiväys',
	256	=>	'Viesti',
	257	=>	'Liitetiedostot:',
	258	=>	'<div align="center"><b>Viesti on tyhjä</b></div>',
	259	=>	'Tätä viestiä ei enää löytynyt, ehkä poistit sen juuri?',
	260	=>	'Edell.',		// unused
	261	=>	'Seur.',		// unused
	262	=>	'Vastaa',
	263	=>	'Vastaa kaikille',
	264	=>	'Poista',
	265	=>	'Lähetä edelleen',
	266	=>	'Näytä viestin otsikkotiedot',
	267	=>	'Ei aihetta',
	268	=>	'Tallenna osoitekirjaan',
	269	=>	'HTML-muotoinen viesti',
	270	=>	'RFC822-muotoinen viesti',
	271	=>	'Lähetyksen tilanne',
	272	=>	'Puhdas tekstimuotoinen viesti',
	273	=>	'RTF-muotoinen viesti',
	274	=>	'Tuntemation muoto',
	275	=>	'Tekstitiedosto',
	276	=>	'Sovellus',
	277	=>	'Äänitiedosto',
	278	=>	'Kuvatiedosto',
	279	=>	'Videokuvatiedosto',
	280	=>	'PGP-allekirjoitus',
	281	=>	'Message Body'
);
?>
