<?php

//--------------------------
// brown theme include file
//--------------------------

// font(s) used in AeroMail

$FONT				= "verdana,arial,helvetica";

// font color

$COLOR_FONT			= "#000000";

// background color

$COLOR_BG			= "#ffffff";

// color for the header

$COLOR_HEAD			= "#996600";
$COLOR_FONT_HEAD		= "#ffffff";

// color for field titles

$COLOR_TITLE			= "#ddcc66";

// color for colored row

$COLOR_ROW_ON			= "#eeeeaa";

// color for uncolored row

$COLOR_ROW_OFF			= "#ffffff";

// link colors

$COLOR_LINK			= "#003399";
$COLOR_VLINK			= "#003399";
$COLOR_ALINK			= "#669966";

?>
