<?
/********************************************************
	lang/se/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$cStrings=array(
	0=>"Kontakter",
	1=>"Lägg till kontakt",
	2=>" Kontakt",
	3=>"Namn",
	4=>"Email",
	5=>"URL",
	6=>"Grupp",
	7=>"Kommentarer",
	8=>"Lägg till/Ändra Kontakt",
	9=>"Email",
    10=>"Skriv"
);

$cErrors=array(
	0=>"Kontaktlistan är tom"
);

?>