<?
/********************************************************
	lang/se/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/
$lang_datetime =  array(
	"dsow" => array (			
			0 => "Sön",
			1 => "Mån",
			2 => "Tis",
			3 => "Ons",
			4 => "Tor",
			5 => "Fre",
			6 => "Lör"
			),
	"today" => "Idag %t",
	"lastweek" => "%w %t",
	"thisyear" => "%m/%d",
	"prevyears" => "%m/%d/%y"
);

?>