<?
/********************************************************
	lang/se/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$efStrings=array(
	0=>"Hantera Mappar",
	1=>"Skapa ny mapp",
	2=>"Skapa mapp: ",
	3=>"Skapa",
	4=>"Ta bort mapp",
	5=>"Ta bort",
	6=>"Döpa om mapp",
	7=>"Döpa om"
);

$errors=array(
	0=>"Skapa mapp: ",
	1=>"Kunde inte skapa mapp: ",
	2=>"Ta bort mapp: ",
	3=>"Kunde inte ta bort mapp: ",
	4=>"Omdöpt mapp: ",
	5=>"Kunde inte döpa om mapp: ",
	6=>"Mappar är endast tillgängliga för IMAP-konton."
);
?>