<?
/********************************************************
	lang/se/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$ecStrings=array(
	0=>"Ändra",
	1=>"Lägg till",
	2=>" Kontakt",
	3=>"Namn",
	4=>"Email",
	5=>"URL",
	6=>"Grupp",
	7=>"Kommentarer",
	8=>"Hemtelefon",
	9=>"Arbetstelefon",
	10=>"Mobiltelefon",
	11=>"Address",
	12=>"Alt. Email",
	13=>"Ta bort",
	14=>"Andra"
);

$errors=array(
	0=>"Kunde inte lägga till kontakt:  databasfel.",
	1=>"En annan kontakt med samma adress finns redan",
	2=>"Klicka ",
	3=>"här",
	4=>" för att redigera kontakten istället.",
	5=>"Hittades ej, eller åtkomst nekad.",
	6=>"Är du säker på att du vill ta bort posten för \"",
	7=>"\"?"
);
?>