<?
/********************************************************
	lang/se/prefs.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>	

********************************************************/

$prefHeaderStrings = array(
											0=> "Inställningar",
											1=>"Generella",
											2=>"Färger"
											);
											
$prefsStrings = array(
									"0.0" => "Identitet",
									"0.1" => "Namn: ",
									"0.2" => "Email: ",
									"1.0" => "Internationell",
									"1.1" => "Gränssnitt: ",
									"1.2" => "Bokstavsuppsättning: ",
									"1.3" => "Tidszon: ",
									"2.0" => "Egenskaper för Listvy",
									"2.1" => "Visa upp till ",
									"2.2" => " poster",
									"2.3" => "Visa storlek",
									"2.4" => "Sortera efter: ",
									"2.5" => "",
									"2.6" => "Sorteringsordning: ",
									"2.7" => "",
									"2.8" => "Visa mapplista",
									"3.0" => "Egenskaper för Auto-Spara",
									"3.1" => "Spara skickade poster.",
									"3.2"=> "Spara skickade meddelande i mapp: ",
									"3.3" => "",
									"3.4" => "Ta bort skräp automatiskt",
									"3.5" => "Flytta borttagna poster till: ",
									"3.6" => "",
									"3.7" => "Rotbibliotek: ",
									"3.8" => "Annan",
									"4.0" => "Egenskaper för Meddelandevy",
									"4.1" => "Visa i ram",
									"4.2" => "Färga citeringar",
									"4.3" => "Denna egenskap kan göra systemet långsammare.",
                                    "4.4" => "Konvertera URLs till länkar",
									"4.5" => "Visa HTML meddelanden",
									"4.6" => "Visa bilder i rad",
									"5.0" => "Signatur",
									"5.1" => "Visa signatur som standard",
									"5.2" => ""
									);

$sort_fields=array("DATE"=>"Datum", "SUBJECT"=>"Ämne", "SIZE"=>"Storlek");
$sort_orders=array("ASC"=>"Ökande", "DESC"=>"Minskande");

$prefsButtonStrings = array( 0=> "Uppdatera", 1=>"Värkställ", 2=> "Avbryt", 3=> "Standardvärden");

$prefs_new_user = "Det verkar som du loggar in för första gången...välkommen!<br>";
$prefs_new_user .= "Gå igenom följande inställningar, tryck därefter \"Verkställ\"";
?>