<?
/********************************************************
	lang/se/pref_colors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$pcStrings= array(
							"0" => "Ange en HTML färgkod för varje komponent.",
							"0.1" => "Använd ",
							"0.2" => "Färgkods tabell",
							"0.3" => " för att hitta rätt färgkoder.",
							"1.0" => "Verktygsfält",
							"2.0" => "Mapplista",
							"3.0" => "Huvud", 
							"4.0" => "Övriga",
							"4.1" => "Citeringar: "
							);
							
$pcPortions = array( "Backgrund: ", "Länkar: ", "Text: ", "Markering: ");

?>