<?
/********************************************************
	lang/se/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$rmStrings=array(
	0=>"Tillbaka",
	1=>"Svara",
	2=>"Vidarebefordra",
	3=>"Ångra ta bort",
	4=>"ta bort",
	5=>"Fil",
	6=>"Delar",
	7=>"Detta är ett HTML meddelande. ",
	8=>"Klicka här för att läsa det.",
	9=>"Källa",
	10=>"Storlek",
	11=>"Markera som Oläst",
	12=>"Visa Huvud",
	13=>"Rapportera Spam",
	14=>"Svara till alla"
);
?>