<?
/********************************************************
	lang/se/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$searchErrors=array(
	"field"=>"Ogilitigt sökkriterium:  Ogiltigt fält",
	"empty"=>"Ogilitigt sökkriterium:  Tom söksträng",
	"date"=>"Ogilitigt sökkriterium:  Datum ej angivet"
);
?>