<?
/********************************************************
	lang/se/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$toolStrings=array(
	"folders"=>"Mappar",
	"inbox"=>"Inkorg",
	"compose"=>"Skriv",
	"contacts"=>"Kontakter",
	"search"=>"Sök",
	"prefs"=>"Inställningar",
	"logout"=>"Logga ut",
	"go"=>"Gå"
);
?>