<?
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"Contacts",
	1=>"Add Contact",
	2=>" Contact",
	3=>"Name",
	4=>"Email",
	5=>"URL",
	6=>"Group",
	7=>"Comments",
	8=>"Add/Edit Contact",
	9=>"Email",
    10=>"Compose"
);

$cErrors=array(
	0=>"Contacts list is empty"
);

?>