<?
/********************************************************
	lang/eng/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime =  array(
	"dsow" => array (			
			0 => "Sun",
			1 => "Mon",
			2 => "Tue",
			3 => "Wed",
			4 => "Thu",
			5 => "Fri",
			6 => "Sat"
			),
	"today" => "Today %t",
	"lastweek" => "%w %t",
	"thisyear" => "%m/%d",
	"prevyears" => "%m/%d/%y"
);

?>