<?
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings=array(
	0=>"Manage Folders",
	1=>"Create new folder",
	2=>"Create folder: ",
	3=>"Create",
	4=>"Delete folder",
	5=>"Delete",
	6=>"Rename folder",
	7=>"Rename"
);

$errors=array(
	0=>"Create folder: ",
	1=>"Could not create folder: ",
	2=>"Deleted folder: ",
	3=>"Could not delete folder: ",
	4=>"Renamed folder: ",
	5=>"Could not rename folder: ",
	6=>"Folder-support is only available for IMAP acounts."
);
?>