<?
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings=array(
	0=>"Edit",
	1=>"Add",
	2=>" Contact",
	3=>"Name",
	4=>"Email",
	5=>"URL",
	6=>"Group",
	7=>"Comments",
	8=>"Home Phone",
	9=>"Work Phone",
	10=>"Cell Phone",
	11=>"Address",
	12=>"Alt. Email",
	13=>"Delete",
	14=>"Other"
);

$errors=array(
	0=>"Couldn't add contact:  database error.",
	1=>"An entry with the address already exists.",
	2=>"Click ",
	3=>"here",
	4=>" to edit that entry instead.",
	5=>"Contact not found, or access denied.",
	6=>"Are you sure you would like to delete entry for \"",
	7=>"\"?"
);
?>