<?
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"Back",
	1=>"Reply",
	2=>"Forward",
	3=>"Undelete",
	4=>"Delete",
	5=>"File",
	6=>"Parts",
	7=>"This is an HTML message. ",
	8=>"Click here to read it.",
	9=>"Source",
	10=>"Size",
	11=>"Mark Unread",
	12=>"Show Header",
	13=>"Report Spam",
	14=>"Reply To All"
);
?>