<?
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings=array(
	"folders"=>"Folders",
	"inbox"=>"Inbox",
	"compose"=>"Compose",
	"contacts"=>"Contacts",
	"search"=>"Search",
	"prefs"=>"Prefs",
	"logout"=>"Logout",
	"go"=>"Go"
);
?>