<?
/********************************************************
	lang/it/compose.inc

	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings=array(
	0=>"Concerne",
	1=>"Da",
	2=>"A",
	3=>"CC",
	4=>"BCC",
	5=>"Data"
);

$composeStrings=array(
	0=>"Nuovo messaggio",
	1=>"Invia messaggio",
	2=>"Invia dati",
	3=>"Inserisci firma",
	4=>"Allega",
	5=>"Mostra contatti",
	6=>"Nascondi contatti",
	7=>"Testo del messaggio:",
	8=>"Aggiungi",
	9=>"In data %d, %s ha scritto:\n",
	10=>"--- Messaggio originale ---\n",
	11=>"Chiudi finestra"
);

$composeErrors=array(
	0=>"Il campo -Concerne- &egrave; vuoto. Inserire un -Concerne- o cliccare ancora su \"".$composeStrings[1]."\" per inviare.",
	1=>"Mittente non specificato.  Inserire il proprio indirizzo e-mail.",
	2=>"Destinatario non specificato.  Inserire l'indirizzo e-mail del destinatario.",
	3=>"Invio fallito",
	4=>"Nessun file ricevuto.",
    5=>"Per prevenire ogni abuso (SPAMMING), &egrave; possibile spedire al massimo a %1 persona (%2 per sessione) ogni %3 secondi."
);
?>
