<?
/********************************************************
	lang/it/contacts.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"Contatti",
	1=>"Aggiungi contatto",
	2=>" Contatto",
	3=>"Nome",
	4=>"Email",
	5=>"URL",
	6=>"Gruppo",
	7=>"Commenti",
	8=>"Aggiungi/Modifica contatto",
	9=>"Email",
    10=>"Scrivi"
);

$cErrors=array(
	0=>"La rubrica è vuota"
);

?>
