<?
/********************************************************
	lang/it/dates.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime =  array(
	"dsow" => array (			
			0 => "Dom",
			1 => "Lun",
			2 => "Mar",
			3 => "Mer",
			4 => "Gio",
			5 => "Ven",
			6 => "Sab"
			),
	"today" => "Oggi, %t",
	"lastweek" => "%w %t",
	"thisyear" => "%m/%d",
	"prevyears" => "%m/%d/%y"
);

?>