<?
/********************************************************
	lang/it/edit_contact.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings=array(
	0=>"Modifica",
	1=>"Aggiungi",
	2=>" Contatto",
	3=>"Nome",
	4=>"Email",
	5=>"URL",
	6=>"Gruppo",
	7=>"Commenti",
	8=>"Tel. privato",
	9=>"Tel. ufficio",
	10=>"Cellulare",
	11=>"Indirizzo",
	12=>"Altra Email",
	13=>"Elimina",
	14=>"Altro"
);

$errors=array(
	0=>"Impossibile aggiungere contatto: errore nel database.",
	1=>"Questo indirizzo esiste già nella rubrica.",
	2=>"Clicca ",
	3=>"qu&iacute;",
	4=>" per modificare questa voce.",
	5=>"Voce non trovata o accesso negato.",
	6=>"Sei sicuro di voler eliminare \"",
	7=>"\"?"
);
?>