<?
/********************************************************
	lang/it/edit_folders.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings=array(
	0=>"Gestisci cartelle",
	1=>"Crea nuova cartella",
	2=>"Crea cartella: ",
	3=>"Crea",
	4=>"Elimina cartella",
	5=>"Elimina",
	6=>"Rinomina cartella",
	7=>"Rinomina"
);

$errors=array(
	0=>"Crea cartella: ",
	1=>"Impossibile creare cartella: ",
	2=>"Cartella eliminata: ",
	3=>"Impossibile eliminare cartella: ",
	4=>"Cartella rinominata: ",
	5=>"Impossibile rinominare cartella: ",
	6=>"La gestione delle cartelle è disponibile solo per il protocollo IMAP."
);
?>