<?
/********************************************************
	lang/it/cp.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings= array(
							"0" => "Inserisci un codice HTML per il colore di ogni elemento.",
							"0.1" => "Utilizza la ",
							"0.2" => "Tabella codici colori",
							"0.3" => " per trovare il colore voluto.",
							"1.0" => "Barra strumenti",
							"2.0" => "Lista cartelle",
							"3.0" => "Principale", 
							"4.0" => "Diversi",
							"4.1" => "Citazione: "
							);
							
$pcPortions = array( "Sfondo: ", "Collegamenti: ", "Testo: ", "Evidenziato: ");

?>