<?
/********************************************************
	lang/it/prefs.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$prefHeaderStrings = array(
											0=> "Preferenze",
											1=>"Generale",
											2=>"Colori"
											);
											
$prefsStrings = array(
									"0.0" => "Identit&agrave;",
									"0.1" => "Nome: ",
									"0.2" => "Email: ",
									"1.0" => "Parametri internazionali",
									"1.1" => "Lingua interfaccia: ",
									"1.2" => "Set di caratteri: ",
									"1.3" => "Fuso orario: ",
									"2.0" => "Opzioni di visualizzazione",
									"2.1" => "Mostra fino a ",
									"2.2" => " elementi",
									"2.3" => "Mostra dimensione",
									"2.4" => "Ordinamento: ",
									"2.5" => "",
									"2.6" => "Ordina per: ",
									"2.7" => "",
									"2.8" => "Mostra lista cartelle",
									"3.0" => "Salvataggio automatico",
									"3.1" => "Salva email inviate.",
									"3.2"=> "Salva i messaggi inviati nella cartella: ",
									"3.3" => "",
									"3.4" => "Svuota automaticamente cestino",
									"3.5" => "Sposta messaggi eliminati nella cartella: ",
									"3.6" => "",
									"3.7" => "Cartella principale (radice): ",
									"3.8" => "Altro",
									"4.0" => "Opzioni di visualizzazione messaggi",
									"4.1" => "Visualizza in una frame",
									"4.2" => "Colora citazioni",
									"4.3" => "Attivare questa opzione potrebbe rallentare il sistema.",
                                                                        "4.4" => "Converti URLs in collegamenti",
									"4.5" => "Mostra messaggi HTML",
									"4.6" => "Includi visualizzazione immagini",
									"5.0" => "Firma",
									"5.1" => "Visualizza la firma",
									"5.2" => ""
									);

$sort_fields=array("DATE"=>"Data", "SUBJECT"=>"Concerne", "SIZE"=>"Dimensione");
$sort_orders=array("ASC"=>"Ascendente", "DESC"=>"Discendente");

$prefsButtonStrings = array( 0=> "Aggiorna", 1=>"Applica", 2=> "Cancella", 3=> "Predefiniti");

$prefs_new_user = "E' la vostra prima visita...benvenuto!<br>";
$prefs_new_user .= "Riempite questo formulario, per favore, e cliccate su \"Applica\"";
?>