<?
/********************************************************
	lang/it/read_message.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"Indietro",
	1=>"Rispondi",
	2=>"Inoltra",
	3=>"Recupera",
	4=>"Cancella",
	5=>"Sposta",
	6=>"Parti",
	7=>"Questo è un messaggio HTML. ",
	8=>"Clicca qu&iacute; per leggerlo.",
	9=>"Sorgente",
	10=>"Dimensione",
	11=>"Segna come non letto",
	12=>"Mostra intestazione",
	13=>"Segnala Spam",
	14=>"Rispondi a tutti"
);
?>