<?
/********************************************************
	lang/it/tool.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings=array(
	"folders"=>"Cartelle",
	"inbox"=>"Posta in arrivo",
	"compose"=>"Scrivi messaggio",
	"contacts"=>"Contatti",
	"search"=>"Cerca",
	"prefs"=>"Preferenzee",
	"logout"=>"Disconnetti",
	"go"=>"OK"
);
?>