<?
/********************************************************
	lang/jp/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$lang_datetime =  array(
	"dsow" => array (			
			0 => "日",
			1 => "月",
			2 => "火",
			3 => "水",
			4 => "木",
			5 => "金",
			6 => "土"
			),
	"today" => "今日 %t",
	"lastweek" => "%t (%w)",
	"thisyear" => "%m月%d日",
	"prevyears" => "%y年%m月%d日"
);

?>