<?
/********************************************************
	lang/eng/cp.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings= array(
							"0" => "各々のパネルの表示色(HTMLカラーコード)を指定してください。",
							"0.1" => "好みの色のカラーコードを",
							"0.2" => "カラーコード表",
							"0.3" => "から探す事もできます。",
							"1.0" => "ツールバー",
							"2.0" => "フォルダーリスト",
							"3.0" => "メイン", 
							"4.0" => "その他",
							"4.1" => "引用文: "
							);
							
$pcPortions = array( "背景: ", "リンク: ", "テキスト: ", "ハイライト: ");

?>
