<?
/********************************************************
	lang/jp/read_message.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	PURPOSE:
		Provide strings for "source/read_message.inc"

********************************************************/

$rmStrings=array(
	0=>"戻る",
	1=>"返信",
	2=>"転送",
	3=>"ゴミ箱から出す",
	4=>"消去",
	5=>"移動",
	6=>"てん付",
	7=>"このメッセージはHTML形式になってます。",
	8=>"ここにクリックすると開きます",
	9=>"ソース表示",
	10=>"容量",
	11=>"未読",
	12=>"ヘッダー",
	13=>"スパム報告",
	14=>"全員へ返信"
);
?>