<?
/********************************************************
	lang/jp/search_errors.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	PURPOSE:
		Error strings for search function.

********************************************************/

$searchErrors=array(
	"field"=>"対象フィールドが指定されていません。",
	"empty"=>"検索項目が指定されていません。",
	"date"=>"日付けが指定されていません。"
);
?>