<?
/********************************************************
	lang/jp/tool.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings=array(
	"folders"=>"フォルダー",
	"inbox"=>"受信箱",
	"compose"=>"作成",
	"contacts"=>"アドレス帳",
	"search"=>"検索",
	"prefs"=>"設定",
	"logout"=>"ログアウト",
	"go"=>"表示"
);
?>