<head>
<style>
.normal    {font-family:arial,arial; color:black; font-size:10pt;}
TD         {font-family:helvetica,arial; color:black; font-size:10pt;}
pre        {font-family:arial,arial; color:black; font-size:10pt;}
A:link     {color:blue; text-decoration: none; font-style: bold; }
A:active   {color:red; text-decoration: none; font-style: bold; }
A:visited  {color:darkblue; text-decoration: none; font-style: bold; }
</style>
</head>
<body bgcolor='#ffffff'>



<table align='center' width='700' bgcolor='#a9a9a9' cellpadding='0' cellspacing='0' border='0'>
<tr>
<td align='right' bgcolor='#ffffff' nowrap>
<b> . : S T A T S</a>
</td>
<tr>
<td>
<table width='100%' bgcolor='#ffffff' cellpadding='4' cellspacing='1' border='0'>
<tr>
<td bgcolor='#eeeeee'>
<font color='crimson'>
<a href='<? echo "$PHP_SELF"; ?>'>Requests</a> |
<a href='<? echo "$PHP_SELF?viewby=url"; ?>'>Top 50 urls</a> |
<a href='<? echo "$PHP_SELF?viewby=referer"; ?>'>Referer</a> |
<a href='<? echo "$PHP_SELF?viewby=agent"; ?>'>Browser</a> |
<a href='<? echo "$PHP_SELF?viewby=os"; ?>'>OS</a>
</font>
</td>
</tr>
<tr>
<td nowrap>
<br>
