<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'U heeft niet opgegeven waar te zoeken, probeer het nog eens.',
	602	=>	'U heeft niet opgegeven wat te zoeken, probeer het nog eens.',
	603	=>	'Ben a.u.b. specifieker',
	604	=>	'Niets gevonden, probeer het nog eens.',
	605	=>	'Uw zoekopdracht leverde %d berichten op.',
	606	=>	'U kunt zoeken naar berichten die een bepaalde tekst bevatten. U kunt zoeken op <u>Van</u>, <u>Onderwerp</u> en <u>Bericht</u> delen van berichten. Geef a.u.b. de folders op waarin gezocht moet worden, geef de zoektekst, en klik op de <b>Zoeken</b> knop.<br><br>Zoeken is <b>niet</b> hoofdlettergevoelig. Als U meer dan een zoekwoord opgeeft, worden alleen de berichten die deze zoekwoorden bevatten in de opgegeven volgorde gevonden.',
	607	=>	'Bericht',
	608	=>	'Onderwerp',
	609	=>	'Van',
	610	=>	'<not used>',
	611	=>	'Zoeken',
	612	=>	'U heeft geen folders opgegeven om in te zoeken.',
	613	=>	'Datum'
);
?>
