<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Ja',
	2	=>	'Nee',
	3	=>	'Maak uw keuze, a.u.b.',
	4	=>	'U moet JavaScript inschakelen om BasiliX efficient te gebruiken',
	5	=>	'U moet CSS ondersteuning inschakelen om BasiliX efficient te gebruiken',
	6	=>	'U moet Cookie ondersteuning inschakelen om  BasiliX efficient te gebruiken',
	7	=>	'Onbekend',
	8	=>	'Printen',
	9	=>	'Sluit Venster',
	10	=>	'Huidig # gebruikers: %d'
);
?>
