<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Uw E-mail Adres',
	52	=>	'Wachtwoord',
	53	=>	'Log in',
	54	=>	'Geef uw wachtwoord om opnieuw in te loggen',
	55	=>	'Andere gebruiker',
	56	=>	'Beveiligde verbinding (kan traag zijn)',
	57	=>	'Onbeveiligde verbinding',
	58	=>	'Vul a.u.b. alle velden in.',
	59	=>	'Vul a.u.b. uw e-mail adres correct in.',
	60	=>	'Vul a.u.b. uw wachtwoord in.',
	61	=>	'Foutief wachtwoord of onjuist e-mail adres.',
	62	=>	'Change domain'
);
?>
