<?
// Messages related with reading a message
$lang_msg["msgs"] = array(
	251	=>	'Van',
	252	=>	'Aan',
	253	=>	'Cc',
	254	=>	'Onderwerp',
	255	=>	'Datum',
	256	=>	'Inhoud bericht',
	257	=>	'Toevoegingen:',
	258	=>	'<div align="center"><b>De inhoud van het bericht is leeg!</b></div>',
	259	=>	'Het opgegeven bericht kon niet gevonden worden, misschien heeft U het zojuist verwijderd!',
	260	=>	'Vorige',		// unused
	261	=>	'Volgende',		// unused
	262	=>	'Antwoord',
	263	=>	'Antwoord Iedereen',
	264	=>	'Verwijder',
	265	=>	'Doorsturen',
	266	=>	'Laat mail-header zien',
	267	=>	'Geen onderwerp',
	268	=>	'Sla adres op',
	269	=>	'HTML Bericht',
	270	=>	'RFC822 Bericht',
	271	=>	'Bezorings status',
	272	=>	'Standaard tekstbericht',
	273	=>	'Uitgebreid tekstbericht',
	274	=>	'Onbekende toevoeging',
	275	=>	'Tekstbericht',
	276	=>	'Applicatie',
	277	=>	'Audio Bestand',
	278	=>	'Grafisch Bestand',
	279	=>	'Video Clip',
	280	=>	'PGP Signatuur',
	281	=>	'Message Body'
);
?>
