<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'Nie poda³e¶ gdzie szukaæ, spróbuj jeszcze raz.',
	602	=>	'Nie poda³e¶ co szukaæ, spróbuj jeszcze raz.',
	603	=>	'Proszê zawêziæ kr±g poszukiwañ',
	604	=>	'Nic nie znaleziono.',
	605	=>	'Znaleziono %d wiadomo¶ci.',
	606	=>	'Mo¿esz przeszukaæ swoje foldery w poszukiwaniu wiadomo¶ci które zawieraj± podany tekst. Mo¿esz wykonaæ wyszukiwanie na polach <u>Od</u>, <u>Temat</u> i <u>Tre¶æ</u>. Wska¿ skrzynkê do przeszukania, podaj pole, i kliknij na <b>Szukaj</b>.<br><br>Szukanie <b>nie</b> rozró¿nia du¿ych i ma³ych liter wiêc je¶li chcesz podaæ wiêcej s³ów, tylko wiadomo¶æ zawieraj±ca te s³owa w odpowiedniej kolejno¶ci bêdzie znaleziona.',
	607	=>	'Tre¶æ',
	608	=>	'Temat',
	609	=>	'Od',
	610	=>	'<niewykorzystane>',
	611	=>	'Szukaj',
	612	=>	'Nie poda³e¶ skrzynek do przeszukania.',
	613	=>	'Data'
);
?>