<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Adres e-mail',
	52	=>	'Has³o',
	53	=>	'Login',
	54	=>	'Podaj has³o aby ponownie siê zalogowaæ',
	55	=>	'Zmieñ u¿ytkownika',
	56	=>	'Bezpieczne po³±czenie (mo¿e byæ wolniejsze)',
	57	=>	'Niebezpieczne po³±czenie',
	58	=>	'Wype³nij wszystkie pola.',
	59	=>	'Wpisz poprawnie adres e-mail.',
	60	=>	'Podaj has³o.',
	61	=>	'Niepoprawne has³o lub nie ma takiego adresu e-mail.',
	62	=>	'Change domain'
);
?>
