<?
// Messages related with reading a message
$lang_msg["msgs"] = array(
	251	=>	'Od',
	252	=>	'Do',
	253	=>	'Cc',
	254	=>	'Temat',
	255	=>	'Data',
	256	=>	'Tre¶æ',
	257	=>	'Za³±czniki:',
	258	=>	'<div align="center"><b>Tre¶æ wiadomo¶ci jest pusta</b></div>',
	259	=>	'Wybrana wiadomo¶æ nie zosta³a znaleziona, mog³e¶ j± skasowaæ!',
	260	=>	'Poprzednia',		// unused
	261	=>	'Nastêpna',		// unused
	262	=>	'Odpowiedz',
	263	=>	'Odpowiedz wszystkim',
	264	=>	'Usuñ',
	265	=>	'Prze¶lij dalej',
	266	=>	'Poka¿ nag³ówek',
	267	=>	'Brak tematu',
	268	=>	'Zapisz adres',
	269	=>	'Format HTML',
	270	=>	'Format RFC822',
	271	=>	'Status dorêczenia',
	272	=>	'Format Plaintext',
	273	=>	'Format Enriched Text',
	274	=>	'Nieznany za³±cznik',
	275	=>	'Wiadomo¶æ tekstowa',
	276	=>	'Aplikacja',
	277	=>	'Zbiór audio',
	278	=>	'Zdjêcie',
	279	=>	'Wideoklip',
	280	=>	'Podpis PGP',
	281	=>	'Message Body'
);
?>
