<?
/*
   File name         : commonhead.inc
   Version           : 1.1.1
   Last Modified By  : Umut Gokbayrak
   e-mail            : umut@trlinux.com
   Purpose           : Common tags used in all HTML files' head section
   Last modified     : 31 Oct 2000
*/

  echo "<html>\n";
  echo "<head>\n";
  echo "<title>$title</title>\n";
  echo "<meta http-equiv='Content-Type' content='text/html; charset=$charset'>\n";
  echo "<meta name='author' content='Umut Gokbayrak'>\n";
?>
