<?
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"Kontakte",
	1=>"Kontakt hinzu",
	2=>" Kontakt",
	3=>"Name",
	4=>"E-Mail",
	5=>"URL",
	6=>"Gruppe",
	7=>"Kommentar",
	8=>"Kontakt hinzu/&auml;ndern",
	9=>"E-Mail",
	10=>"Neue Nachricht"
);

$cErrors=array(
	0=>"Liste der Kontakte ist leer"
);
?>)