<?
/********************************************************
	lang/eng/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime =  array(
	"dsow" => array (			
			0 => "So",
			1 => "Mo",
			2 => "Di",
			3 => "Mi",
			4 => "Do",
			5 => "Fr",
			6 => "Sa"
			),
	"today" => "Heute %t",
	"lastweek" => "%w %t",
	"thisyear" => "%d.%m.",
	"prevyears" => "%d.%m.%y"
);

?>