<?
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings=array(
	0=>"&Auml;ndern",
	1=>"Hinzu",
	2=>" Kontakt",
	3=>"Name",
	4=>"E-Mail",
	5=>"URL",
	6=>"Gruppe",
	7=>"Kommentare",
	8=>"Tel. privat",
	9=>"Tel. B&uuml;ro",
	10=>"Tel. mobil",
	11=>"Adresse",
	12=>"Weitere E-Mail",
	13=>"L&ouml;schen",
	14=>"Andere"
);

$errors=array(
	0=>"Kontakt konnte nicht hinzugef&uuml;gt werden (Datenbankfehler).",
	1=>"Ein Eintrag mit dieser Adresse existiert bereits.",
	2=>"Klicken Sie ",
	3=>"hier",
	4=>" um diesen Eintrag zu &auml;ndern.",
	5=>"Kontakt nicht gefunden, oder Zugriff verweigert.",
	6=>"Soll der Eintrag f&uuml;r \"",
	7=>"\" wirklich gel&ouml;scht werden?"
);
?>