<?
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings=array(
	0=>"Ordnerverwaltung",
	1=>"Neuer Ordner",
	2=>"Neuer Ordner: ",
	3=>"Neu",
	4=>"Ordner l&ouml;schen",
	5=>"L&ouml;schen",
	6=>"Ordner umbenennen",
	7=>"Umbenennen"
);

$errors=array(
	0=>"Neuer Ordner: ",
	1=>"Konnte neuen Ordner nicht anlegen: ",
	2=>"Ordner gel&ouml;scht: ",
	3=>"Konnte Ordner nicht l&ouml;schen: ",
	4=>"Ordner umbenannt: ",
	5=>"Konnte Ordner nicht umbenennen: ",
	6=>"Ordner werden nur unterst&uuml;tzt, wenn der Server mit dem IMAP Protokoll arbeitet."
);
?>