<?/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html
********************************************************/

$pcStrings= array(
	"0" => "Geben Sie bitte f&uuml;r die einzelnen Elemente einen HTML-Farbcode ein.",
	"0.1" => "(Sie k&ouml;nnem die Codes in der ",
	"0.2" => "Farbtabelle",
	"0.3" => " nachschlagen.)",
	"1.0" => "Men&uuml;leiste",
	"2.0" => "Ordnerliste",
	"3.0" => "Hauptfenster",
	"4.0" => "Div.",
	"4.1" => "Zitate: "
	);
	
$pcPortions = array( "Hintergrund: ", "Verweise: ", "Text: ", "Hervorhebung: ");?>
