<?
/********************************************************
	lang/eng/prefs.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$prefHeaderStrings = array(
    0=> "Einstellungen",
    1=>"Allgemein",
    2=>"Farben"
    );
											
$prefsStrings = array(
    "0.0" => "Identit&auml;t",
    "0.1" => "Name: ",
    "0.2" => "E-Mail: ",
    "1.0" => "Sprache und Zeichensatz",
    "1.1" => "Benutzerf&uuml;hrung: ",
    "1.2" => "Zeichensatz: ",
    "1.3" => "Zeitzone: ",
    "2.0" => "Listenansicht",
    "2.1" => "Zeige bis zu ",
    "2.2" => " Eintr&auml;ge",
    "2.3" => "Gr&ouml;&szlig;e anzeigen",
    "2.4" => "Sortiere nach: ",
    "2.5" => "",
    "2.6" => "Sortierung: ",
    "2.7" => "",
    "2.8" => "Ordnerliste anzeigen",
    "3.0" => "Automatisches Speichern",
    "3.1" => "Gesendete Nachrichten speichern.",
    "3.2" => "Gesendete in Ordner ",
    "3.3" => " ablegen",
    "3.4" => "Papierkorb automatisch leeren",
    "3.5" => "Gel&ouml;schte Nachrichten in Ordner: ",
    "3.6" => " ablegen",
    "3.7" => "Wurzelverzeichnis: ",
    "3.8" => "Anderes Verzeichnis",
    "4.0" => "Nachrichtenanzeige",
    "4.1" => "In Frame anzeigen",
    "4.2" => "Zitate in Farbe",
    "4.3" => "(Diese Option verlangsamt m&ouml;glicherweise das System.)",
    "4.4" => "URLs als Links anzeigen",
    "4.5" => "HTML Nachrichten anzeigen",
    "4.6" => "Bilder direkt im Text zeigen",
    "5.0" => "Unterschrift",
    "5.1" => "Unterschrift standardm&auml;ssig einf&uuml;gen",
    "5.2" => ""
);

$sort_fields=array("DATE"=>"Datum", "SUBJECT"=>"Betreff", "SIZE"=>"Gr&ouml;&szlig;e");
$sort_orders=array("ASC"=>"aufsteigend", "DESC"=>"absteigend");

$prefsButtonStrings = array( 0=> "Speichern", 1=> "Fertig", 2=> "Verwerfen", 3=> "Standardeinstellungen");

$prefs_new_user = "Sie scheinen das erste Mal einzuloggen ... Willkommen!<br>";
$prefs_new_user .= "Bitte nehmen Sie sich einen Moment Zeit, die folgenden Einstellungen zu &uuml;berpr&uuml;fen und ggf. anzupassen, und dr&uuml;cken Sie dann auf SPEICHERN,";
?>)