<?
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"Zur&uuml;ck",
	1=>"Antworten",
	2=>"Weiterleiten",
	3=>"Gel&ouml;schte wiederherstellen",
	4=>"L&ouml;schen",
	5=>"Verschieben",
	6=>"parts",
	7=>"Diese Nachricht ist im HTML Format. ",
	8=>"Klicken Sie hier, um sie zu lesen.",
	9=>"Quelle",
	10=>"Gr&ouml;sse",
	11=>"Als ungelesen markieren",
	12=>"Mail-Header anzeigen",
	13=>"Spam-Beschwerde",
	14=>"Antwort an alle"
);
?>