<?
// 'Find message' messages
$lang_msg["findmsg"] = array(
	601	=>	'You haven\'t specified where to search, please try again.',
	602	=>	'You haven\'t specified what to search, please try again.',
	603	=>	'Please be more specific',
	604	=>	'No match found, please try again.',
	605	=>	'Your query matches %d messages.',
	606	=>	'You can search your mail folders for those messages which contain a certain text. You can perform search on <u>From</u>, <u>Subject</u> and <u>Body</u> parts of messages. Please select the mailboxes to be searched, enter the textname, and click on the <b>Search</b> button.<br><br>Search is <b>not</b> case sensitive so if you enter more than one keyword, only the messages containing those keywords in the specified order will be found.',
	607	=>	'Body',
	608	=>	'Subject',
	609	=>	'From',
	610	=>	'<not used>',
	611	=>	'Search',
	612	=>	'You haven\'t specified the mailboxes to be searched.',
	613	=>	'Date',
	614	=>	'check all',
	615	=>	'uncheck all'
);
?>
