<?
// Global messages
$lang_msg["global"] = array(
	1	=>	'Yes',
	2	=>	'No',
	3	=>	'Please select',
	4	=>	'You must enable JavaScript for your browser to use BasiliX efficient',
	5	=>	'You must enable CSS support for your browser to use BasiliX efficient',
	6	=>	'You must enable Cookie support for your browser to use BasiliX efficient',
	7	=>	'Unknown',
	8	=>	'Print',
	9	=>	'Close',
	10	=>	'Current # of users: %d'
);
?>
