<?
// Login messages
$lang_msg["login"] = array(
	51	=>	'Your E-mail Address',
	52	=>	'Password',
	53	=>	'Login',
	54	=>	'Please enter your password to re-login',
	55	=>	'Change user',
	56	=>	'Secure connection (SSL)',
	57	=>	'Normal connection',
	58	=>	'Please fill all the fields.',
	59	=>	'Please enter your e-mail address correctly.',
	60	=>	'Please enter your password.',
	61	=>	'Incorrect password or no such e-mail address.',
	62	=>	'Change domain'
);
?>
